Repository helpscout/hsds-react, pull requests merged in 2018-08, with the labels that each got.

#325 Animate: Improve rendering for Safari (iOS)
  src/components/Animate/styles/Animate.css.js
Labels: bug 🐛, stability 💪

#324 PropProvider: A configurable Blue. Unlocked!
  src/components/PropProvider/Consumer.js
  src/components/PropProvider/Context.js
  src/components/PropProvider/Provider.js
  src/components/PropProvider/README.md
  src/components/PropProvider/__tests__/Provider.test.js
  src/components/PropProvider/__tests__/configConnect.test.js
  src/components/PropProvider/configConnect.js
  src/components/PropProvider/docs/Provider.md
  src/components/PropProvider/docs/configConnect.md
  src/components/PropProvider/index.js
  src/components/PropProvider/utils.js
  src/components/README.md
  src/components/Tooltip/index.js
  src/components/index.js
  stories/Tooltip.js
  todos/README.md
  todos/components.md
  todos/design.md
  todos/workflow.md
Labels: enhancement ✨, feature 💅

#326 Input: onResize callback + Enhance propConnect/PropProvider
  README.md
  package-lock.json
  package.json
  src/components/Input/Input.js
  src/components/Input/README.md
  src/components/Input/__tests__/Input.test.js
  src/components/Input/index.js
  src/components/Popper/Manager.js
  src/components/PreviewCard/Context.js
  src/components/PropProvider/Context.js
  src/components/PropProvider/README.md
  src/components/PropProvider/__tests__/Provider.test.js
  src/components/PropProvider/__tests__/propConnect.test.js
  src/components/PropProvider/__tests__/utils.test.js
  src/components/PropProvider/configConnect.js
  src/components/PropProvider/docs/configConnect.md
  src/components/PropProvider/docs/propConnect.md
  src/components/PropProvider/index.js
  src/components/PropProvider/propConnect.js
  src/components/PropProvider/utils.js
  src/components/Tooltip/Tooltip.js
  src/components/Tooltip/index.js
  stories/Input.js
Labels: enhancement ✨, feature 💅, refactor ♻️

#327 Message: Timestamp interaction refactor
  src/components/HoverWrapper/README.md
  src/components/HoverWrapper/index.js
  src/components/HoverWrapper/tests/HoverWrapper.test.js
  src/components/Message/Attachment.js
  src/components/Message/Bubble.js
  src/components/Message/Chat.js
  src/components/Message/ChatBlock.js
  src/components/Message/Content.js
  src/components/Message/__tests__/Bubble.test.js
  src/components/Message/__tests__/ChatBlock.test.js
  src/components/Message/__tests__/Message.test.js
  src/components/Message/__tests__/Question.test.js
  src/components/Message/docs/ChatBlock.md
  src/components/Message/index.js
  src/components/Message/styles/ChatBlock.css.js
  src/components/README.md
  src/components/Timeline/Item.js
  src/components/Timeline/Timeline.js
  src/components/Timeline/__tests__/Item.test.js
  src/components/Timeline/__tests__/Timeline.test.js
  src/components/Timeline/docs/Item.md
  src/components/Timeline/index.js
  src/components/index.js
  src/styles/components/Timeline/TimelineItem.scss
  stories/Message/media.js
Labels: bug 🐛, enhancement ✨, refactor ♻️

#328 Fancy: Hoist statics for styled components
  package-lock.json
  package.json
  src/components/Attachment/Attachment.js
  src/components/Attachment/__tests__/Attachment.test.js
  src/components/Attachment/index.js
  src/components/Input/Backdrop.js
  src/components/Link/index.js
  src/components/Message/Message.js
Labels: enhancement ✨, refactor ♻️

#329 IE: Improve rendering stability
  src/components/InfiniteScroller/index.js
  src/components/Input/Input.js
  src/components/Message/Attachment.js
  src/components/Message/Bubble.js
  src/components/Message/styles/Bubble.css.js
  src/utilities/smoothScroll.js
Labels: stability 💪

#330 Message: Support Embedded HTML Content
  src/components/Message/Embed.js
  src/components/Message/Message.js
  src/components/Message/README.md
  src/components/Message/__tests__/Embed.test.js
  src/components/Message/docs/Embed.md
  src/components/Message/styles/Embed.css.js
  stories/Message/embed.js
  stories/Message/index.js
Labels: enhancement ✨

#331 Message: Fix Bubble border-radius
  src/components/Message/styles/Chat.css.js
  stories/Message/index.js
Labels: bug 🐛

#334 ButtonV2!
  src/components/Button/ButtonV2.js
  src/components/Button/README.md
  src/components/Button/__tests__/ButtonV2.test.js
  src/components/Button/docs/ButtonV1.md
  src/components/Button/docs/ButtonV2.md
  src/components/Button/styles/Button.css.js
  src/components/Button/types.js
  src/components/Icon/Icon.js
  src/components/Icon/__tests__/Icon.test.js
  src/components/Icon/index.js
  src/components/Icon/styles/Icon.css.js
  src/components/Icon/utils.js
  src/components/index.js
  stories/Button/ButtonV2.js
  stories/Button/index.js
  stories/ControlGroup/index.js
  stories/Page/Actions.js
Labels: enhancement ✨, feature 💅
