Repository helpscout/hsds-react, pull requests merged in 2018-10, with the labels that each got.

#367 Only call highlightBlock if the ref element is not null
  src/components/CopyCode/CopyCode.js
  src/components/CopyCode/README.md
  src/components/Highlight/Highlight.js
Labels: bug 🐛

#368 Add loading indicator to Message.Embed
  src/components/Message/Embed.js
  src/components/Message/__tests__/Embed.test.js
  src/components/Message/styles/Embed.css.js
Labels: enhancement ✨

#372 Input/Choice updates
  src/components/Button/ButtonV2.js
  src/components/Button/styles/Button.css.js
  src/components/ChoiceGroup/ChoiceGroup.js
  src/components/ChoiceGroup/README.md
  src/components/ChoiceGroup/__tests__/ChoiceGroup.test.js
  src/components/ChoiceGroup/styles/ChoiceGroup.css.js
  src/components/CopyButton/CopyButton.js
  src/components/CopyInput/CopyInput.js
  src/components/CopyInput/__tests__/CopyInput.test.js
  src/components/FormGroup/Choice.js
  src/components/FormGroup/__tests__/FormGroup.Choice.test.js
  src/components/FormGroup/__tests__/FormGroup.test.js
  src/components/FormGroup/docs/Choice.md
  src/components/FormGroup/styles/Choice.css.js
  src/components/Input/Input.js
  src/components/Input/Prefix.js
  src/components/Input/Suffix.js
  src/components/Input/__tests__/Input.test.js
  src/components/Input/__tests__/Prefix.test.js
  src/components/Input/__tests__/Suffix.test.js
  src/components/Input/docs/Input.md
  src/components/Input/index.js
  src/components/Input/styles/BackdropV2.css.js
  src/components/Input/styles/Input.css.js
  src/components/Input/utils.js
  src/components/Message/Embed.js
  src/components/RadioCard/styles/RadioCard.css.js
  src/styles/external/emoji-mart.scss
  stories/Input.js
  stories/RadioCard/index.js
  stories/index.js
Labels: enhancement ✨

#374 Make Blue More Blue
  .vscode/settings.json
Labels: enhancement ✨

#373 Choice + Other component adjustments
  package-lock.json
  package.json
  src/components/Choice/styles/Choice.css.js
  src/components/ChoiceGroup/ChoiceGroup.js
  src/components/ChoiceGroup/README.md
  src/components/CopyCode/CopyCode.js
  src/components/CopyCode/__tests__/CopyCode.test.js
  src/components/CopyCode/styles/CopyCode.css.js
  src/components/FormGroup/Choice.js
  src/components/FormGroup/docs/Choice.md
  src/components/Page/Header.js
  src/components/Page/__tests__/Header.test.js
  src/components/Page/docs/Header.md
  src/components/Page/styles/Card.css.js
  src/components/Page/styles/Header.css.js
  src/components/RadioCard/styles/RadioCard.css.js
  stories/Page/Card.js
  stories/RadioCard/index.js
Labels: enhancement ✨

#378 RadioCard: Add Focus UI
  package-lock.json
  package.json
  src/components/RadioCard/RadioCard.js
  src/components/RadioCard/__tests__/RadioCard.test.js
  src/components/RadioCard/styles/RadioCard.css.js
  stories/RadioCard/index.js
Labels: enhancement ✨

#382 Card list component
  src/components/CardList/CardList.js
  src/components/CardList/README.md
  src/components/CardList/__tests__/CardList.test.js
  src/components/CardList/index.js
  src/components/CardList/utils.js
  src/components/README.md
  src/components/index.js
  src/utilities/component.js
  stories/CardList.js
  stories/index.js
Labels: enhancement ✨

#386 Grid: Refactor + CSS-in-JS
  package-lock.json
  package.json
  src/components/Grid/Col.js
  src/components/Grid/Container.js
  src/components/Grid/Grid.js
  src/components/Grid/Row.js
  src/components/Grid/__tests__/Col.test.js
  src/components/Grid/__tests__/Container.test.js
  src/components/Grid/__tests__/Grid.test.js
  src/components/Grid/__tests__/Row.test.js
  src/components/Grid/index.js
  src/components/Grid/styles/Col.css.js
  src/components/Grid/styles/Container.css.js
  src/components/Grid/styles/Row.css.js
  src/components/Grid/tests/Container.test.js
  src/components/Grid/tests/Row.test.js
  src/components/Grid/utils.js
  src/styles/components/ChatInbox/ChatInbox.scss
  src/styles/components/FormGroup/__index.scss
  src/styles/components/Grid.scss
  src/styles/components/Message/__index.scss
  src/styles/mixins/breakpoints.css.js
  stories/Grid.js
Labels: enhancement ✨, refactor ♻️

#387 Skeleton: Refactor + CSS-in-JS
  .babelrc
  .storybook/.babelrc
  package-lock.json
  package.json
  src/components/RadioCard/RadioCard.js
  src/components/RadioCard/__tests__/RadioCard.test.js
  src/components/Skeleton/Avatar.js
  src/components/Skeleton/Block.js
  src/components/Skeleton/Control.js
  src/components/Skeleton/Heading.js
  src/components/Skeleton/Image.js
  src/components/Skeleton/Paragraph.js
  src/components/Skeleton/Text.js
  src/components/Skeleton/__tests__/Avatar.test.js
  src/components/Skeleton/__tests__/Block.test.js
  src/components/Skeleton/__tests__/Control.test.js
  src/components/Skeleton/__tests__/Heading.test.js
  src/components/Skeleton/__tests__/Image.test.js
  src/components/Skeleton/__tests__/Paragraph.test.js
  src/components/Skeleton/__tests__/Text.test.js
  src/components/Skeleton/docs/Avatar.md
  src/components/Skeleton/docs/Block.md
  src/components/Skeleton/docs/Control.md
  src/components/Skeleton/docs/Heading.md
  src/components/Skeleton/docs/Image.md
  src/components/Skeleton/docs/Paragraph.md
  src/components/Skeleton/docs/Text.md
  src/components/Skeleton/index.js
  src/components/Skeleton/styles/Avatar.css.js
  src/components/Skeleton/styles/Block.css.js
  src/components/Skeleton/styles/Control.css.js
  src/components/Skeleton/styles/Image.css.js
  src/components/Skeleton/styles/Text.css.js
  src/components/Skeleton/tests/Block.test.js
  src/components/Skeleton/utils.js
  src/styles/components/Skeleton/SkeletonAvatar.scss
  src/styles/components/Skeleton/SkeletonBlock.scss
  src/styles/components/Skeleton/SkeletonControl.scss
  src/styles/components/Skeleton/SkeletonImage.scss
  src/styles/components/Skeleton/SkeletonParagraph.scss
  src/styles/components/Skeleton/SkeletonText.scss
  src/styles/components/Skeleton/__index.scss
  stories/RadioCard/index.js
  stories/Skeleton.js
Labels: bug 🐛, enhancement ✨, refactor ♻️

#389 Icon: Add plus icon
  package-lock.json
  package.json
  scripts/update-icons.js
  src/components/Icon/icons.js
  src/icons/plus-large.svg
  src/icons/plus-small.svg
Labels: enhancement ✨

#391 AvatarStack + Avatar - Version 2!
  src/components/Animate/Animate.js
  src/components/Animate/__tests__/Animate.test.js
  src/components/Animate/index.js
  src/components/Animate/styles/Animate.css.js
  src/components/Animate/utils.js
  src/components/AnimateGroup/AnimateGroup.js
  src/components/AnimateGroup/__tests__/AnimateGroup.test.js
  src/components/AnimateGroup/index.js
  src/components/AnimateGroup/utils.js
  src/components/Avatar/Avatar.js
  src/components/Avatar/AvatarV2.js
  src/components/Avatar/README.md
  src/components/Avatar/__tests__/Avatar.test.js
  src/components/Avatar/__tests__/AvatarV2.test.js
  src/components/Avatar/index.js
  src/components/Avatar/styles/Avatar.css.js
  src/components/AvatarStack/AvatarStack.js
  src/components/AvatarStack/AvatarStackV2.js
  src/components/AvatarStack/README.md
  src/components/AvatarStack/__tests__/AvatarStack.test.js
  src/components/AvatarStack/__tests__/AvatarStackV2.test.js
  src/components/AvatarStack/index.js
  src/components/AvatarStack/styles/AvatarStack.css.js
  src/components/CardList/CardList.js
  src/components/CardList/__tests__/CardList.test.js
  src/components/Modal/__tests__/Modal.test.js
  src/components/PropProvider/__tests__/PropProvider.test.js
  src/components/PropProvider/propConnect.js
  src/utilities/__tests__/component.test.js
  src/utilities/__tests__/number.test.js
  src/utilities/component.js
  src/utilities/number.js
  stories/Avatar/AvatarV2.js
  stories/Avatar/index.js
  stories/Avatar/specs/Avatar.js
  stories/AvatarStack/AvatarStackV2.js
  stories/AvatarStack/index.js
  stories/CardList.js
Labels: enhancement ✨, feature 💅, refactor ♻️, stability 💪

#392 Input: ScrollToBottom to account for padding
  src/components/Input/Input.js
  src/components/Input/__tests__/Input.test.js
  stories/Input.js
Labels: enhancement ✨

#393 Add bubble icons
  src/components/Icon/icons.js
  src/icons/arrow-left.svg
  src/icons/bubble-dots-duplicate.svg
  src/icons/bubble-dots-plus.svg
  stories/Icon.js
Labels: enhancement ✨

#394 Button V2: Allow content events to pass through
  src/components/Button/ButtonV2.js
  src/components/Button/__tests__/ButtonV2.test.js
  src/components/Button/docs/ButtonV2.md
  src/components/Button/index.js
  src/components/Button/styles/Button.css.js
  stories/Button/ButtonV2.js
Labels: bug 🐛, enhancement ✨

#395 Input: Remove key press event for scrollToBottom
  package-lock.json
  package.json
  src/components/Input/Input.js
  src/components/Input/__tests__/Input.test.js
Labels: bug 🐛

#396 Add Artboard!
  package-lock.json
  package.json
  stories/AvatarStack/AvatarStackV2.js
Labels: enhancement ✨
