Repository helpscout/hsds-react, pull requests merged in 2018-11, with the labels that each got.

#397 Message.Chat: Fix bubble radius
  src/components/Message/styles/Chat.css.js
  stories/Message/chat.js
Labels: bug 🐛

#398 Fancy: Fix iFrame rendering for Edge/iFrame
  package-lock.json
  package.json
  stories/Fancy/FrameProvider.js
Labels: bug 🐛

#401 AvatarList: Fix duplicate avatars
  .gitignore
  package-lock.json
  src/components/AvatarList/AvatarList.js
  src/components/AvatarList/AvatarList.tsx
  src/components/AvatarList/__tests__/AvatarList.test.js
  src/components/AvatarList/index.js
  src/components/AvatarList/index.ts
  stories/AvatarList.stories.js
Labels: bug 🐛

#400 Dropdown V2!
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/DropdownV2.ts
  src/components/Dropdown/README.md
  src/components/Dropdown/V2/Dropdown.Container.tsx
  src/components/Dropdown/V2/Dropdown.Item.tsx
  src/components/Dropdown/V2/Dropdown.Menu.tsx
  src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
  src/components/Dropdown/V2/Dropdown.Trigger.tsx
  src/components/Dropdown/V2/Dropdown.actions.ts
  src/components/Dropdown/V2/Dropdown.css.js
  src/components/Dropdown/V2/Dropdown.store.js
  src/components/Dropdown/V2/Dropdown.tsx
  src/components/Dropdown/V2/Dropdown.types.ts
  src/components/Dropdown/V2/Dropdown.utils.ts
  src/components/Dropdown/V2/__tests__/Dropdown.Item.test.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.Menu.test.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.MenuContainer.test.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.Trigger.test.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.actions.test.ts
  src/components/Dropdown/V2/__tests__/Dropdown.test.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.testHelpers.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.utils.test.tsx
  src/components/Dropdown/V2/__tests__/DropdownV2.test.tsx
  src/components/Dropdown/V2/docs/Dropdown.md
  src/components/Dropdown/V2/index.ts
  src/components/Dropdown/__tests__/Dropdown.test.js
  src/components/EventListener/EventListener.tsx
  src/components/EventListener/__tests__/EventListener.test.js
  src/components/EventListener/index.js
  src/components/EventListener/index.ts
  src/components/Icon/Icon.js
  src/components/KeypressListener/KeypressListener.tsx
  src/components/KeypressListener/__tests__/KeypressListener.test.js
  src/components/KeypressListener/index.ts
  src/utilities/__tests__/is.test.js
  src/utilities/__tests__/scrolling.test.js
  src/utilities/component.ts
  src/utilities/is.ts
  src/utilities/scrolling.js
  stories/DropdownV2.stories.js
Labels: enhancement ✨, feature 💅

#404 Icons: Add mailbox action icons
  src/components/Icon/icons.js
  src/icons/note.svg
  src/icons/pencil-small.svg
  src/icons/reply.svg
  src/icons/status.svg
  src/icons/tag.svg
  src/icons/workflow-small.svg
  src/icons/workflow.svg
  stories/Icon.stories.js
Labels: enhancement ✨

#407 FormLabel: Adds a new mode (inline)
  package-lock.json
  src/components/FormLabel/FormLabel.tsx
  src/components/FormLabel/README.md
  src/components/FormLabel/__tests__/FormLabel.test.js
  src/components/FormLabel/styles/FormLabel.css.ts
  stories/FormLabel.stories.js
  stories/Page/Page.Card.stories.js
Labels: enhancement ✨

#411 Move help text inside the label when Choice is stacked
  src/components/Choice/Choice.js
  src/components/Choice/__tests__/Choice.test.js
Labels: enhancement ✨

#410 Notification: Update UI + Refactor
  .storybook/addons.js
  package-lock.json
  package.json
  src/components/Message/styles/Bubble.css.js
  src/components/Message/styles/ChatBlock.css.js
  src/components/Notification/Notification.css.js
  src/components/Notification/Notification.tsx
  src/components/Notification/Timer.tsx
  src/components/Notification/__tests__/Notification.test.js
  src/components/Notification/__tests__/Timer.test.js
  src/components/Notification/index.js
  src/components/Notification/index.ts
  src/components/Notification/utils.ts
  src/components/NotificationStack/NotificationStack.css.js
  src/components/NotificationStack/NotificationStack.tsx
  src/components/NotificationStack/__tests__/NotificationStack.test.js
  src/components/NotificationStack/index.js
  src/components/NotificationStack/index.ts
  src/components/NotificationStack/utils.ts
  src/styles/components/Notification/Notification.scss
  src/styles/components/Notification/NotificationTimer.scss
  src/styles/components/Notification/__index.scss
  src/styles/components/NotificationStack.scss
  stories/Notification.stories.js
  stories/NotificationStack.stories.js
Labels: enhancement ✨

#413 ArticleCard: UI Updates
  .eslintrc
  package-lock.json
  package.json
  src/components/ArticleCard/ArticleCard.tsx
  src/components/ArticleCard/__tests__/ArticleCard.test.js
  src/components/ArticleCard/index.ts
  src/components/ArticleCard/styles/ArticleCard.css.js
  src/components/AvatarStack/styles/AvatarStack.css.js
  src/styles/mixins/cardStyles.css.js
  stories/ArticleCard.stories.js
Labels: enhancement ✨
