Repository helpscout/hsds-react, pull requests merged in 2018-07, with the labels that each got.

#293 Fancy 2.0 Update 👩‍🎤
  package-lock.json
  package.json
  src/components/Emoticon/index.js
  src/components/Emoticon/styles/Emoticon.css.js
  src/components/Emoticon/types.js
  src/components/Huzzah/index.js
  src/components/Huzzah/styles/Huzzah.css.js
  src/components/Illo/index.js
  src/components/Input/README.md
  src/components/Input/__tests__/Input.test.js
  src/components/Input/__tests__/helpers.test.js
  src/components/Input/helpers.js
  src/components/Input/index.js
  src/components/Pop/Arrow.js
  src/components/Pop/styles/PopArrow.css.js
  src/components/ScrollLock/index.js
  src/components/Tooltip/Popper.js
  src/components/Tooltip/__tests__/Popper.test.js
  src/components/Tooltip/__tests__/Tooltip.test.js
  src/components/Tooltip/index.js
  src/components/Tooltip/styles/Tooltip.css.js
  src/components/Tooltip/styles/TooltipPopper.css.js
  src/components/Truncate/__tests__/Truncate.test.js
  src/components/Truncate/index.js
  src/components/Truncate/styles/Truncate.css.js
  src/components/VisuallyHidden/__tests__/VisuallyHidden.test.js
  src/components/VisuallyHidden/index.js
  src/components/VisuallyHidden/styles/VisuallyHidden.css.js
  src/components/styled/__tests__/styled.test.js
  src/components/styled/index.js
  src/components/styled/testHelpers.js
  src/styles/components/Icon.scss
  src/styles/components/Illo.scss
  src/styles/components/Truncate.scss
  src/styles/components/VisuallyHidden.scss
  src/styles/components/__index.scss
  src/styles/mixins/visuallyHidden.css.js
  src/utilities/__tests__/classNames.test.js
  src/utilities/classNames.js
  stories/Fancy/FrameProvider.js
  stories/Fancy/ScopeProvider.js
  stories/Fancy/ThemeProvider.js
  stories/Fancy/index.js
  stories/index.js
Labels: enhancement ✨

#294 Attachments: Improve overflow handling
  package.json
  src/components/Attachment/Provider.js
  src/components/Attachment/__tests__/Attachment.test.js
  src/components/Attachment/index.js
  src/components/Attachment/styles/Attachment.css.js
  src/components/Attachment/types.js
  src/components/AttachmentList/__tests__/AttachmentList.test.js
  src/components/AttachmentList/index.js
  src/components/AttachmentList/styles/AttachmentList.css.js
  src/components/CloseButton/index.js
  src/components/Input/index.js
  src/components/Overflow/__tests__/Overflow.test.js
  src/components/Overflow/index.js
  src/components/Overflow/styles/Overflow.css.js
  src/components/Pop/Popper.js
  src/components/Pop/index.js
  src/components/Pop/types.js
  src/components/ScrollLock/index.js
  src/components/Tooltip/__tests__/Tooltip.test.js
  src/components/Tooltip/index.js
  src/components/Truncate/__tests__/Truncate.test.js
  src/components/Truncate/index.js
  src/styles/components/Animate.scss
  src/styles/components/Animate/Animate.scss
  src/styles/components/Attachment.scss
  src/styles/components/AttachmentList.scss
  src/styles/components/Overflow.scss
  src/styles/configs/colors.js
  src/styles/mixins/cardStyles.css.js
  src/styles/mixins/linkStyles.css.js
  src/styles/mixins/visuallyHidden.css.js
  src/styles/utilities/__tests__/color.js
  src/styles/utilities/color.js
  src/utilities/__tests__/events.test.js
  src/utilities/__tests__/scrolling.test.js
  src/utilities/events.js
  src/utilities/scrolling.js
  src/utilities/smoothScroll.js
  stories/AttachmentList/index.js
Labels: enhancement ✨, refactor ♻️

#295 AttachmentList: Improve UX on new items
  .flowconfig
  package.json
  src/components/Attachment/styles/Attachment.css.js
  src/components/AttachmentList/__tests__/AttachmentList.test.js
  src/components/AttachmentList/index.js
  src/components/Overflow/__tests__/Overflow.test.js
  src/components/Overflow/index.js
  stories/AttachmentList/index.js
Labels: enhancement ✨, refactor ♻️

#297 Is typing events for inputs
  src/components/Input/README.md
  src/components/Input/__tests__/Input.test.js
  src/components/Input/index.js
  stories/Input.js
Labels: enhancement ✨

#298 Message.Media/Image: Responsive aspect ratio support
  src/components/Image/README.md
  src/components/Image/index.js
  src/components/Image/tests/Image.test.js
  src/components/Input/index.js
  src/components/Message/Media.js
  src/components/Message/__tests__/Media.test.js
  src/components/Message/docs/Media.md
  src/components/Message/styles/Media.css.js
  src/styles/mixins/breakpoints.css.js
  src/utilities/__tests__/is.test.js
  src/utilities/images.js
  src/utilities/is.js
  stories/Message/media.js
Labels: enhancement ✨

#299 Message.Media: Add thumbanil support + fix close button
  src/components/Message/Media.js
  src/components/Message/__tests__/Media.test.js
  src/components/Message/docs/Media.md
  src/components/Message/styles/Media.css.js
  src/components/Modal/index.js
  stories/Message/media.js
Labels: enhancement ✨

#300 Adding refApplySubmit to input
  src/components/Input/README.md
  src/components/Input/__tests__/Input.test.js
  src/components/Input/index.js
  stories/Input.js
Labels: enhancement ✨

#302 Change refApplySubmit to refApplyCallStopTyping
  src/components/Input/README.md
  src/components/Input/__tests__/Input.test.js
  src/components/Input/index.js
  stories/Input.js
Labels: enhancement ✨

#301 Message.Media: Adjust styles
  package.json
  src/components/Collapsible/__tests__/Collapsible.test.js
  src/components/Message/styles/Media.css.js
  src/components/Timestamp/__tests__/Timestamp.test.js
  src/styles/components/Card/Card.scss
  src/styles/mixins/cardStyles.css.js
  src/styles/mixins/cardStyles.scss
  stories/Message/media.js
Labels: enhancement ✨

#303 Fixes onStopTyping so it doesn't fire if there is no timeout
  src/components/Input/index.js
Labels: bug 🐛

#304 Test: Refactor tests to use jest.useFakeTimeout
  src/components/Modal/tests/Modal.test.js
  src/components/Portal/index.js
  src/components/Portal/tests/Portal.test.js
  src/components/PortalWrapper/tests/PortalWrapper.test.js
Labels: refactor ♻️, stability 💪

#305 Update dependencies and resolve Flow issues
  package-lock.json
  package.json
  src/components/ChoiceGroup/index.js
  src/components/Dropdown/Menu.js
  src/components/Emoticon/index.js
  src/components/Illo/index.js
  src/components/Input/index.js
  src/components/Sortable/index.js
  src/utilities/arrays.js
  src/utilities/easing.js
  src/utilities/strings.js
Labels: enhancement ✨, refactor ♻️, stability 💪

#306 Fancy: Update babel build
  package-lock.json
  package.json
  src/components/Dropdown/__tests__/Menu.test.js
Labels: stability 💪

#307 Message.Content: Note theme
  src/components/Message/ChatBlock.js
  src/components/Message/Content.js
  src/components/Message/Media.js
  src/components/Message/Message.js
  src/components/Message/__tests__/Content.test.js
  src/components/Message/__tests__/Message.test.js
  src/components/Message/docs/Content.md
  src/components/Message/docs/Message.md
  src/components/Message/styles/Content.css.js
  src/components/Message/styles/Media.css.js
  src/components/Message/types.js
  src/components/PreviewCard/Context.js
  src/components/PreviewCard/__tests__/PreviewCard.test.js
  src/components/PreviewCard/index.js
  src/components/PreviewCard/styles/PreviewCard.css.js
  src/styles/components/Message/Content.scss
  src/styles/components/PreviewCard.scss
  src/styles/mixins/noteStyles.css.js
  stories/Message/index.js
Labels: enhancement ✨, refactor ♻️, stability 💪

#308 Message.Note: Fix isNote prop for rendering
  src/components/Message/Action.js
Labels: bug 🐛

#309 Message: Improve isNote prop/rendering
  .vscode/settings.json
  src/components/Message/Content.js
  src/components/Message/Media.js
  src/components/Message/Message.js
  src/components/Message/__tests__/Message.test.js
  src/components/Message/styles/Content.css.js
  src/components/PreviewCard/styles/PreviewCard.css.js
  stories/Message/index.js
Labels: bug 🐛, refactor ♻️, stability 💪

#310 Icon: Fancy styles
  src/components/Animate/tests/Animate.test.js
  src/components/Icon/__tests__/Icon.test.js
  src/components/Icon/index.js
  src/components/Icon/propTypes.js
  src/components/Icon/styles/Icon.css.js
  src/components/Icon/tests/Icon.test.js
  src/components/Icon/types.js
  src/components/Overflow/__tests__/Overflow.test.js
  src/components/SidebarCollapsibleCard/tests/SidebarCollapsibleCard.test.js
  src/components/Tooltip/styles/Tooltip.css.js
  src/styles/components/Icon.scss
  src/styles/configs/colors.js
Labels: enhancement ✨, refactor ♻️

#312 Styles: Minor cleanup + improvements
  src/styles/mixins/breakpoints.css.js
  src/styles/resets/baseStyles.css.js
  src/styles/resets/font.css.js
  src/styles/utilities/variableFontSize.js
Labels: enhancement ✨, refactor ♻️

#313 Modal: Fix close button repositioning
  package-lock.json
  package.json
  src/components/Badge/__tests__/Badge.test.js
  src/components/Badge/index.js
  src/components/Badge/styles/Badge.css.js
  src/components/Badge/tests/Badge.test.js
  src/components/Heading/README.md
  src/components/Heading/__tests__/Heading.test.js
  src/components/Heading/index.js
  src/components/Heading/styles/Heading.css.js
  src/components/Modal/index.js
  src/components/Text/README.md
  src/components/Text/__tests__/Text.test.js
  src/components/Text/index.js
  src/components/Text/styles/Text.css.js
  src/constants/types.js
  src/styles/components/Badge.scss
  src/styles/configs/colors.js
  src/styles/configs/constants.js
  src/styles/utilities/__tests__/color.test.js
  src/styles/utilities/__tests__/variableFontSize.test.js
  src/styles/utilities/color.js
  src/styles/utilities/variableFontSize.js
  stories/Text.js
Labels: bug 🐛, enhancement ✨, refactor ♻️, stability 💪

#314 Modal: Close fix
  src/components/Attachment/index.js
  src/components/Modal/Body.js
  src/components/Modal/index.js
  src/components/Modal/styles/Body.css.js
  src/components/Modal/tests/Body.test.js
  src/components/Modal/tests/Modal.test.js
  src/styles/components/Modal/ModalBody.scss
Labels: bug 🐛, refactor ♻️

#315 AvatarGrid: Remove animation
  src/components/AvatarGrid/README.md
  src/components/AvatarGrid/__tests__/AvatarGrid.test.js
  src/components/AvatarGrid/index.js
  src/components/AvatarGrid/styles/AvatarGrid.css.js
  src/components/AvatarGrid/styles/AvatarGridContainer.css.js
  src/components/AvatarGrid/styles/AvatarGridWrapper.css.js
  src/styles/components/AvatarGrid.scss
  stories/AvatarGrid/index.js
Labels: bug 🐛, enhancement ✨, refactor ♻️

#316 Add a throttler to throttle startTyping events
  src/components/Input/README.md
  src/components/Input/__tests__/Input.test.js
  src/components/Input/index.js
Labels: enhancement ✨

#318 Fix documentation for input
  src/components/Input/README.md
Labels: documentation 🖋

#317 Message: Convert SCSS to Fancy CSS-in-JS
  src/components/Heading/styles/Heading.css.js
  src/components/Heading/types.js
  src/components/Message/Action.js
  src/components/Message/Attachment.js
  src/components/Message/Bubble.js
  src/components/Message/Caption.js
  src/components/Message/Chat.js
  src/components/Message/ChatBlock.js
  src/components/Message/Message.js
  src/components/Message/__tests__/Action.test.js
  src/components/Message/__tests__/Attachment.test.js
  src/components/Message/__tests__/Bubble.test.js
  src/components/Message/__tests__/Chat.test.js
  src/components/Message/__tests__/ChatBlock.test.js
  src/components/Message/__tests__/Message.test.js
  src/components/Message/__tests__/Provider.test.js
  src/components/Message/styles/Action.css.js
  src/components/Message/styles/Attachment.css.js
  src/components/Message/styles/Bubble.css.js
  src/components/Message/styles/Chat.css.js
  src/components/Message/styles/ChatBlock.css.js
  src/components/Message/styles/Message.css.js
  src/components/Notification/tests/Notification.test.js
  src/components/Text/styles/Text.css.js
  src/styles/components/Message/Action.scss
  src/styles/components/Message/Attachment.scss
  src/styles/components/Message/Bubble.scss
  src/styles/components/Message/Chat.scss
  src/styles/components/Message/ChatBlock.scss
  src/styles/components/Message/Message.scss
  src/styles/components/Message/__index.scss
  src/styles/components/Notification/Notification.scss
Labels: enhancement ✨, refactor ♻️, stability 💪

#320 Truncate: Improve calculation reliability
  src/components/Pop/styles/Pop.css.js
  src/components/Pop/styles/PopArrow.css.js
  src/components/Tooltip/styles/Tooltip.css.js
  src/components/Tooltip/styles/TooltipPopper.css.js
  src/components/Truncate/__tests__/Truncate.test.js
  src/components/Truncate/index.js
  src/components/Truncate/propTypes.js
  src/components/Truncate/styles/Truncate.css.js
  stories/Truncate.js
Labels: bug 🐛, enhancement ✨

#321 Animate: CSS - Refactor with Fancy
  src/components/Animate/__tests__/Animate.test.js
  src/components/Animate/index.js
  src/components/Animate/propTypes.js
  src/components/Animate/styles/Animate.css.js
  src/components/Animate/styles/sequences/down.css.js
  src/components/Animate/styles/sequences/fade.css.js
  src/components/Animate/styles/sequences/index.css.js
  src/components/Animate/styles/sequences/left.css.js
  src/components/Animate/styles/sequences/right.css.js
  src/components/Animate/styles/sequences/scale.css.js
  src/components/Animate/styles/sequences/up.css.js
  src/components/Animate/styles/sequences/upUp.css.js
  src/components/Animate/types.js
  src/components/Select/index.js
  src/styles/components/Animate.scss
  src/styles/components/Animate/Animate.scss
  src/styles/components/Animate/__index.scss
  src/styles/components/Animate/sequences/__index.scss
  src/styles/components/Animate/sequences/_left.scss
  src/styles/resets/base.css.js
  src/styles/resets/font.css.js
  src/styles/resets/fontFamily.css.js
  stories/Tooltip.js
Labels: enhancement ✨, refactor ♻️, stability 💪

#322 CSS: Add font family fallbacks for variables
  README.md
  package-lock.json
  src/components/Select/index.js
  src/styles/configs/constants.js
  src/styles/resets/font.css.js
  src/styles/resets/fontFamily.css.js
  src/styles/utilities/variableFontSize.js
Labels: enhancement ✨, stability 💪

#323 Portal: Fallback render to CLOSEST document
  package-lock.json
  package.json
  src/components/Dropdown/Menu.js
  src/components/Message/Bubble.js
  src/components/Portal/index.js
  src/components/Portal/tests/Portal.test.js
  src/components/PortalWrapper/index.js
  src/utilities/__tests__/component/getComponentDefaultProp.test.js
  src/utilities/__tests__/component/isComponent.test.js
  src/utilities/__tests__/react.test.js
  src/utilities/__tests__/types.test.js
  src/utilities/classNames.js
  src/utilities/component.js
  src/utilities/index.js
  src/utilities/react.js
  src/utilities/types.js
  stories/Fancy/FrameProvider.js
  stories/Tooltip.js
Labels: bug 🐛, enhancement ✨
