Repository helpscout/hsds-react, pull requests merged in 2018-09, with the labels that each got.

#338 Do not enlarge images
  src/components/Image/__tests__/Image.test.js
  src/utilities/images.js
  stories/Image.js
Labels: bug 🐛

#340 Illo: Fix size rendering for Firefox
  src/components/Illo/Illo.js
  src/components/Illo/__tests__/Illo.test.js
  src/components/Illo/__tests__/injectFillColorIntoSvg.test.js
  src/components/Illo/index.js
  src/components/Illo/styles/Illo.css.js
  src/components/Illo/utils.js
Labels: bug 🐛

#341 Switch: Add loading state
  src/components/Switch/README.md
  src/components/Switch/Switch.js
  src/components/Switch/__tests__/Switch.test.js
  src/components/Switch/styles/Switch.css.js
  stories/Switch.js
Labels: enhancement ✨

#342 Switch: Fix `onChange`/`onClick` callbacks
  src/components/Switch/Switch.js
  src/components/Switch/__tests__/Switch.test.js
  stories/Switch.js
Labels: bug 🐛

#343 Switch/ChoiceInput: Bug fixes
  package-lock.json
  package.json
  src/components/Choice/Choice.js
  src/components/Choice/Input.js
  src/components/Choice/__tests__/Choice.test.js
  src/components/Choice/__tests__/ChoiceInput.test.js
  src/components/Switch/Switch.js
  src/components/Switch/__tests__/Switch.test.js
  src/components/Switch/styles/Switch.css.js
  stories/Switch.js
Labels: bug 🐛

#339 Fix status dots for color blindness
  src/components/StatusBadge/tests/StatusBadge.test.js
  src/components/StatusDot/StatusDot.js
  src/components/StatusDot/__tests__/StatusDot.test.js
  src/components/StatusDot/index.js
  src/components/StatusDot/propTypes.js
  src/components/StatusDot/styles/StatusDot.css.js
  src/components/StatusDot/types.js
  src/components/StatusDot/utils.js
  src/styles/components/StatusDot.scss
  test/acceptance/components/StatusDot.spec.js
Labels: enhancement ✨, refactor ♻️

#344 Add styles for disabled state on the Switch component
  src/components/Switch/Switch.js
  src/components/Switch/__tests__/Switch.test.js
  src/components/Switch/styles/Switch.css.js
  stories/Switch.js
Labels: enhancement ✨

#346 Fix Codesandbox Integration
  package-lock.json
  package.json
  src/components/EventListener/index.js
  src/components/KeypressListener/index.js
  src/components/Label/Label.js
Labels: bug 🐛

#347 Switch: Update onChange callback values
  src/components/Switch/README.md
  src/components/Switch/Switch.js
  src/components/Switch/__tests__/Switch.test.js
  stories/Switch.js
Labels: enhancement ✨

#348 FluffyCard + OptionTile components
  package-lock.json
  package.json
  src/components/Card/Block.js
  src/components/Card/Card.js
  src/components/Card/__tests__/Card.Block.test.js
  src/components/Card/__tests__/Card.test.js
  src/components/Card/index.js
  src/components/Card/styles/Block.css.js
  src/components/Card/styles/Card.css.js
  src/components/Card/utils.js
  src/components/FluffyCard/Container.js
  src/components/FluffyCard/FluffyCard.js
  src/components/FluffyCard/README.md
  src/components/FluffyCard/__tests__/Container.test.js
  src/components/FluffyCard/__tests__/FluffyCard.test.js
  src/components/FluffyCard/docs/Container.md
  src/components/FluffyCard/docs/FluffyCard.md
  src/components/FluffyCard/index.js
  src/components/FluffyCard/styles/Container.css.js
  src/components/FluffyCard/styles/FluffyCard.css.js
  src/components/FluffyCard/types.js
  src/components/FluffyCard/utils.js
  src/components/OptionIcon/OptionIcon.js
  src/components/OptionIcon/README.md
  src/components/OptionIcon/__tests__/OptionIcon.test.js
  src/components/OptionIcon/index.js
  src/components/OptionIcon/styles/OptionIcon.css.js
  src/components/OptionIcon/utils.js
  src/components/OptionTile/Container.js
  src/components/OptionTile/OptionTile.js
  src/components/OptionTile/README.md
  src/components/OptionTile/__tests__/OptionTile.test.js
  src/components/OptionTile/docs/Container.md
  src/components/OptionTile/docs/OptionTile.md
  src/components/OptionTile/index.js
  src/components/OptionTile/styles/OptionTile.css.js
  src/components/OptionTile/utils.js
  src/components/Text/Text.js
  src/components/Text/__tests__/Text.test.js
  src/components/Text/styles/Text.css.js
  src/components/index.js
  src/components/styled/brandColor.md
  src/styles/components/Card/Card.scss
  src/styles/components/Card/CardBlock.scss
  src/styles/components/Card/__index.scss
  src/styles/includePaths.js
  src/styles/utilities/__tests__/color.test.js
  src/styles/utilities/color.js
  src/tests/libraries/helix/withReactComponents.test.js
  src/utilities/get.js
  stories/FluffyCard/index.js
  stories/OptionIcon/index.js
  stories/OptionTile/index.js
  stories/index.js
Labels: enhancement ✨, feature 💅

#351 Flexy: Refactor with CSS-in-JS
  package-lock.json
  package.json
  src/components/Choice/Input.js
  src/components/Flexy/Block.js
  src/components/Flexy/Flexy.js
  src/components/Flexy/Item.js
  src/components/Flexy/__tests__/Block.test.js
  src/components/Flexy/__tests__/Flexy.test.js
  src/components/Flexy/__tests__/Item.test.js
  src/components/Flexy/index.js
  src/components/Flexy/styles/Block.css.js
  src/components/Flexy/styles/Flexy.css.js
  src/components/Flexy/styles/Item.css.js
  src/components/Flexy/utils.js
  src/styles/components/Flexy.scss
  stories/Flexy.js
  stories/Flexy/index.js
Labels: enhancement ✨, refactor ♻️

#356 Component tweaks and enhancements for Chat
  package-lock.json
  package.json
  src/components/Avatar/Avatar.js
  src/components/Avatar/__tests__/Avatar.test.js
  src/components/Avatar/styles/Avatar.css.js
  src/components/Message/Action.js
  src/components/Message/Bubble.js
  src/components/Message/__tests__/Action.test.js
  src/components/Message/__tests__/Message.test.js
  src/components/Message/index.js
  src/components/Message/styles/Bubble.css.js
  src/components/Message/styles/ChatBlock.css.js
  src/components/StatusAvatar/StatusAvatar.js
  src/components/StatusAvatar/__tests__/StatusAvatar.test.js
  src/components/StatusAvatar/index.js
  src/components/StatusAvatar/utils.js
  src/components/StatusDot/StatusDot.js
  src/components/StatusDot/styles/StatusDot.css.js
  src/components/Text/README.md
  src/components/Text/Text.js
  src/components/Text/__tests__/Text.test.js
  src/components/Text/styles/Text.css.js
  stories/Avatar/index.js
Labels: enhancement ✨, refactor ♻️

#357 Avatar group component fixes
  package-lock.json
  package.json
  src/components/Avatar/README.md
  src/components/AvatarGrid/AvatarGrid.js
  src/components/AvatarGrid/README.md
  src/components/AvatarGrid/__tests__/AvatarGrid.test.js
  src/components/AvatarList/AvatarList.js
  src/components/AvatarList/README.md
  src/components/AvatarList/__tests__/AvatarList.test.js
  src/components/AvatarStack/AvatarStack.js
  src/components/AvatarStack/README.md
  src/components/AvatarStack/__tests__/AvatarStack.test.js
  stories/AvatarGrid/index.js
Labels: bug 🐛, documentation 🖋, enhancement ✨

#358 ChatInbox/ChatList: Tweaks
  .vscode/extensions.json
  src/components/ChatInbox/ChatInbox.js
  src/components/ChatInbox/Content.js
  src/components/ChatInbox/Header.js
  src/components/ChatInbox/__tests__/ChatInbox.test.js
  src/components/ChatInbox/__tests__/Content.test.js
  src/components/ChatInbox/__tests__/Header.test.js
  src/components/ChatInbox/index.js
  src/components/ChatInbox/styles/ChatInbox.css.js
  src/components/ChatInbox/styles/Content.css.js
  src/components/ChatInbox/styles/Header.css.js
  src/components/ChatInbox/utils.js
  src/components/ChatList/BlankSlate.js
  src/components/ChatList/ChatList.js
  src/components/ChatList/Item.js
  src/components/ChatList/__tests__/BlankSlate.test.js
  src/components/ChatList/__tests__/ChatList.test.js
  src/components/ChatList/__tests__/Item.test.js
  src/components/ChatList/index.js
  src/components/ChatList/propTypes.js
  src/components/ChatList/styles/BlankSlate.css.js
  src/components/ChatList/styles/ChatList.css.js
  src/components/ChatList/styles/Item.css.js
  src/components/ChatList/utils.js
  src/components/ChatScroller/tests/ChatScroller.test.js
  src/components/ChatSidebar/ChatSidebar.js
  src/components/ChatSidebar/__tests__/ChatSidebar.test.js
  src/components/ChatSidebar/index.js
  src/components/ChatSidebar/styles/ChatSidebar.css.js
  src/components/ChatSidebar/utils.js
  src/components/Hr/Hr.js
  src/components/Hr/styles/Hr.css.js
  src/styles/components/ChatInbox/ChatInboxContent.scss
  src/styles/components/ChatInbox/ChatInboxHeader.scss
  src/styles/components/ChatInbox/__index.scss
  src/styles/components/ChatList/ChatList.scss
  src/styles/components/ChatList/ChatListBlankSlate.scss
  src/styles/components/ChatList/ChatListItem.scss
  src/styles/components/ChatList/__index.scss
  src/styles/components/ChatSidebar.scss
Labels: enhancement ✨, refactor ♻️, stability 💪

#359 PropProvider: Enhance to extends prop configs
  package-lock.json
  src/components/PropProvider/Consumer.js
  src/components/PropProvider/Context.js
  src/components/PropProvider/PropProvider.js
  src/components/PropProvider/Provider.js
  src/components/PropProvider/README.md
  src/components/PropProvider/__tests__/PropProvider.test.js
  src/components/PropProvider/__tests__/Provider.test.js
  src/components/PropProvider/__tests__/propConnect.test.js
  src/components/PropProvider/__tests__/utils.test.js
  src/components/PropProvider/docs/PropProvider.md
  src/components/PropProvider/docs/Provider.md
  src/components/PropProvider/index.js
  src/components/PropProvider/propConnect.js
  src/components/PropProvider/types.js
  src/components/PropProvider/utils.js
  src/utilities/__tests__/is.test.js
  src/utilities/is.js
Labels: enhancement ✨

#364 Icon: Add new icons
  src/components/Icon/icons.js
  src/icons/arrow-left-double-large.svg
  src/icons/arrow-left-single-large.svg
  src/icons/arrow-right-double-large.svg
  src/icons/arrow-right-single-large.svg
  src/icons/trash.svg
Labels: enhancement ✨
