Repository helpscout/hsds-react, pull requests merged in 2018-12, with the labels that each got.

#416 Fix HelpText state and add stories
  src/components/HelpText/HelpText.js
  src/components/HelpText/__tests__/HelpText.test.js
  stories/HelpText.stories.tsx
Labels: bug 🐛

#415 Fancy: Update to use PureComponent by default
  package-lock.json
  package.json
  src/components/Message/Message.js
  src/components/Message/__tests__/Action.test.js
  src/components/Message/__tests__/Message.test.js
  src/components/Message/__tests__/Provider.test.js
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/Truncate/__tests__/Truncate.test.js
  stories/Message/Message.Provider.stories.js
Labels: enhancement ✨

#414 Improve build size
  .babelrc
  package-lock.json
  package.json
  src/utilities/get.js
Labels: enhancement ✨

#417 CloseButton: UI + interaction updates
  src/components/CloseButton/CloseButton.css.js
  src/components/CloseButton/CloseButton.tsx
  src/components/CloseButton/CloseButton.types.ts
  src/components/CloseButton/CloseButton.utils.ts
  src/components/CloseButton/__tests__/CloseButton.test.tsx
  src/components/CloseButton/index.js
  src/components/CloseButton/index.ts
  src/components/CloseButton/types.js
  src/components/Modal/Modal.js
  src/components/Modal/__tests__/Modal.test.js
  src/components/Modal/styles/Modal.css.js
  src/styles/components/Checkbox.scss
  src/styles/components/CloseButton.scss
Labels: enhancement ✨

#423 Remove pluralize dependency
  package-lock.json
  package.json
  src/components/ChatSidebar/ChatSidebar.js
  src/utilities/__tests__/pluralize.test.ts
  src/utilities/pluralize.ts
Labels: enhancement ✨

#422 Remove polished. Write own rgba method
  package-lock.json
  package.json
  src/components/ArticleCard/styles/ArticleCard.css.js
  src/components/Dropdown/V2/Dropdown.css.js
  src/components/Notification/Notification.css.js
  src/styles/mixins/cardStyles.css.js
  src/styles/utilities/color.js
  src/utilities/__tests__/color/rgba.test.js
  src/utilities/color.js
Labels: enhancement ✨

#421 Add info icon from Scout icons
  src/components/Icon/icons.js
  src/icons/info.svg
Labels: enhancement ✨

#424 Tooltip + Modal Fixes
  package-lock.json
  package.json
  src/components/Modal/index.js
  src/components/Pop/Popper.js
  src/components/Pop/__tests__/Pop.test.js
  src/components/Pop/__tests__/Popper.test.js
  src/components/Pop/index.js
  src/components/Popper/Popper.js
  src/components/Portal/index.js
  src/components/Portal/tests/Portal.test.js
  src/components/Tooltip/Tooltip.js
  src/components/Tooltip/styles/Tooltip.css.js
  stories/Tooltip.stories.js
Labels: bug 🐛, enhancement ✨

#425 SelectDropdown + AutoDropdown
  src/components/AutoDropdown/AutoDropdown.tsx
  src/components/AutoDropdown/AutoDropdown.utils.ts
  src/components/AutoDropdown/README.md
  src/components/AutoDropdown/__tests__/AutoDropdown.test.tsx
  src/components/AutoDropdown/index.ts
  src/components/ComboBox/ComboBox.tsx
  src/components/ComboBox/README.md
  src/components/Dropdown/V2/Dropdown.Card.tsx
  src/components/Dropdown/V2/Dropdown.Container.tsx
  src/components/Dropdown/V2/Dropdown.Item.tsx
  src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
  src/components/Dropdown/V2/Dropdown.actionTypes.ts
  src/components/Dropdown/V2/Dropdown.actions.ts
  src/components/Dropdown/V2/Dropdown.reducer.ts
  src/components/Dropdown/V2/Dropdown.store.js
  src/components/Dropdown/V2/Dropdown.types.ts
  src/components/Select/Select.Arrows.tsx
  src/components/Select/Select.css.ts
  src/components/Select/Select.js
  src/components/SelectDropdown/README.md
  src/components/SelectDropdown/SelectDropdown.css.ts
  src/components/SelectDropdown/SelectDropdown.tsx
  src/components/SelectDropdown/SelectDropdown.utils.ts
  src/components/SelectDropdown/__tests__/SelectDropdown.test.tsx
  src/components/SelectDropdown/index.ts
  src/components/index.js
  src/styles/components/Select/SelectIcon.scss
  stories/AutoDropdown.stories.js
  stories/SelectDropdown.stories.js
Labels: enhancement ✨, feature 💅

#426 List: Refactor and remove seed-list
  package-lock.json
  package.json
  src/components/Dropdown/V2/Dropdown.Card.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.Container.test.tsx
  src/components/List/Item.js
  src/components/List/List.Item.tsx
  src/components/List/List.css.ts
  src/components/List/List.js
  src/components/List/List.tsx
  src/components/List/List.types.ts
  src/components/List/List.utils.ts
  src/components/List/__tests__/List.Item.test.js
  src/components/List/__tests__/List.test.js
  src/components/List/index.ts
  src/components/List/tests/List.test.js
  src/styles/components/List.scss
  src/styles/includePaths.js
  stories/List.stories.js
Labels: enhancement ✨

#427 Portal: Performance update
  package-lock.json
  package.json
  src/components/Portal/index.js
  src/components/PortalWrapper/Content.js
  src/components/PortalWrapper/Content.tsx
  src/components/PortalWrapper/PortalWrapper.js
  src/components/PortalWrapper/__tests__/Content.test.js
  src/components/PortalWrapper/__tests__/PortalWrapper.test.js
  src/components/PortalWrapper/index.js
  stories/Portal.stories.js
Labels: enhancement ✨, stability 💪

#428 Modal: Prevent className/style prop pass
  src/components/Modal/Modal.js
  stories/Modal.stories.js
Labels: bug 🐛

#430 Input + Is
  package-lock.json
  package.json
  src/components/Input/Input.js
  src/utilities/__tests__/is.test.js
  src/utilities/component.ts
  src/utilities/is.ts
Labels: enhancement ✨

#431 Article Card Updates
  src/components/ArticleCard/ArticleCard.tsx
  src/components/ArticleCard/README.md
  src/components/ArticleCard/__tests__/ArticleCard.test.js
  src/components/ArticleCard/styles/ArticleCard.css.js
  stories/ArticleCard.stories.js
Labels: enhancement ✨

#432 DropdownV2 Improvements + Input/Select.css.js
  package-lock.json
  package.json
  src/components/AvatarList/AvatarList.tsx
  src/components/AvatarList/__tests__/AvatarList.test.js
  src/components/ComboBox/ComboBox.css.ts
  src/components/ComboBox/ComboBox.tsx
  src/components/ComboBox/README.md
  src/components/ComboBox/__tests__/ComboBox.test.tsx
  src/components/CopyInput/__tests__/CopyInput.test.js
  src/components/Dropdown/V2/Dropdown.Container.tsx
  src/components/Dropdown/V2/Dropdown.utils.ts
  src/components/Dropdown/V2/__tests__/Dropdown.Container.test.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.utils.test.tsx
  src/components/Input/Input.js
  src/components/Input/__tests__/Input.test.js
  src/components/Input/styles/Input.css.js
  src/components/Select/Select.css.ts
  src/components/Select/Select.js
  src/components/Select/__tests__/Select.test.js
  src/styles/components/Input/Input.scss
  src/styles/components/Input/InputField.scss
  src/styles/components/Select/Select.scss
  src/styles/mixins/backdrop-styles.scss
  src/styles/mixins/cardStyles.scss
  src/styles/mixins/input-styles.scss
  src/styles/mixins/visually-hidden.scss
  stories/AutoDropdown.stories.js
  stories/DropdownV2.stories.js
Labels: bug 🐛, enhancement ✨, refactor ♻️, stability 💪

#433 Add Remake
  .eslintignore
  .prettierignore
  .remake/component/remake-name/README.md
  .remake/component/remake-name/__tests__/remake-name.test.tsx
  .remake/component/remake-name/index.ts
  .remake/component/remake-name/remake-name.css.ts
  .remake/component/remake-name/remake-name.tsx
  .remake/component/remake-name/remake-name.utils.ts
  .vscode/tasks.json
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement ✨, feature 💅, tooling :wrench:

#434 ChatScroller: Enable external selector
  .remake/component/remake-name/remake-name.tsx
  src/components/ChatScroller/ChatScroller.tsx
  src/components/ChatScroller/ChatScroller.utils.ts
  src/components/ChatScroller/README.md
  src/components/ChatScroller/__tests__/ChatScroller.test.js
  src/components/ChatScroller/index.ts
  src/utilities/smoothScroll.js
  stories/ChatScroller.stories.js
  tsconfig.json
Labels: enhancement ✨

#435 Portal/Modal Fixes
  package-lock.json
  package.json
  src/components/Modal/Body.js
  src/components/Modal/Modal.js
  src/components/Modal/__tests__/Modal.test.js
  src/components/Portal/index.js
  stories/Modal.stories.js
Labels: enhancement ✨, stability 💪
