Repository helpscout/hsds-react, pull requests merged in 2019-12, with the labels that each got.

#759 Update Dropdown Component `window` reference
  src/components/Dropdown/V2/Dropdown.Container.tsx
  src/components/Dropdown/V2/Dropdown.Item.tsx
  src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
  src/components/Dropdown/V2/Dropdown.MenuContainer.utils.ts
  src/components/Dropdown/V2/Dropdown.renderUtils.ts
  src/components/Dropdown/V2/Dropdown.tsx
  src/components/Dropdown/V2/Dropdown.types.ts
  src/components/Dropdown/V2/__tests__/Dropdown.MenuContainer.utils.test.ts
  src/components/Dropdown/V2/docs/Dropdown.md
Labels: enhancement ✨

#718 Update Avatar loading flow
  package-lock.json
  src/components/Avatar/Avatar.Crop.tsx
  src/components/Avatar/Avatar.Image.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/Avatar.types.ts
  src/components/Avatar/Avatar.utils.ts
  src/components/Avatar/__tests__/Avatar.test.js
  src/components/Avatar/styles/Avatar.css.ts
  stories/Avatar/Avatar.stories.js
  stories/ChatList/ChatList.stories.js
Labels: enhancement ✨

#762 HSDS Scope Provider
  .storybook/config.js
  jest.config.js
  package-lock.json
  package.json
  src/components/ActionSelect/ActionSelect.ContentResizer.tsx
  src/components/Avatar/Avatar.Crop.tsx
  src/components/Avatar/Avatar.Image.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/Avatar.types.ts
  src/components/Avatar/Avatar.utils.ts
  src/components/Avatar/__tests__/Avatar.test.js
  src/components/Avatar/styles/Avatar.css.ts
  src/components/Choice/Choice.Input.tsx
  src/components/Dropdown/V2/Dropdown.Container.tsx
  src/components/Dropdown/V2/Dropdown.Item.tsx
  src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
  src/components/Dropdown/V2/Dropdown.MenuContainer.utils.ts
  src/components/Dropdown/V2/Dropdown.renderUtils.ts
  src/components/Dropdown/V2/Dropdown.tsx
  src/components/Dropdown/V2/Dropdown.types.ts
  src/components/Dropdown/V2/__tests__/Dropdown.MenuContainer.utils.test.ts
  src/components/Dropdown/V2/docs/Dropdown.md
  src/components/Form/Actions/Form.Actions.css.js
  src/components/Form/Form.js
  src/components/Form/Form.stories.js
  src/components/Form/Form.test.js
  src/components/Form/README.md
  src/components/GlobalStyle/index.js
  src/components/HSDS/GlobalStyle.js
  src/components/HSDS/Provider.js
  src/components/HSDS/README.md
  src/components/HSDS/docs/GlobalStyle.md
  src/components/HSDS/docs/Provider.md
  src/components/HSDS/index.js
  src/components/Message/Message.utils.ts
  src/components/RouteWrapper/RouteWrapper.tsx
  src/components/ScopeProvider/ScopeProvider.js
  src/components/ScopeProvider/index.js
  src/components/index.ts
  src/components/styled/index.ts
  src/utilities/pkg.ts
  stories/Avatar/Avatar.stories.js
  stories/Fancy/ScopeProvider.stories.js
Labels: enhancement ✨, v3

#763 Input Error and Tooltip Accessibility
  package-lock.json
  package.json
  src/components/Input/Input.tsx
  src/components/Input/Input.types.ts
  src/components/Input/__tests__/Input.test.js
  src/components/Pop/Pop.tsx
  src/components/Pop/__tests__/Pop.test.js
  src/components/Select/Select.tsx
  src/components/Select/Select.types.ts
  src/components/Select/__tests__/Select.test.js
  src/utilities/pkg.ts
  stories/Input.stories.js
  stories/Popover.stories.js
  stories/Tooltip.stories.js
Labels: a11y, enhancement ✨
