Repository helpscout/hsds-react, pull requests merged in 2019-02, with the labels that each got.

#459 Testing: Add Cypress!
  .eslintrc
  .gitignore
  cypress.json
  cypress/README.md
  cypress/fixtures/example.json
  cypress/integration/Button.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/tsconfig.json
  package-lock.json
  package.json
  src/components/Accordion/utils.js
  src/components/Flexy/utils.ts
  src/components/FluffyCard/utils.js
  src/components/Grid/utils.js
  src/components/Modal/utils.js
  src/components/Page/docs/Page.md
  src/components/PropProvider/__tests__/propConnect.test.js
  src/components/PropProvider/propConnect.tsx
  src/utilities/other.ts
  stories/ArticleCard.stories.js
  tsconfig.json
Labels: tooling :wrench:

#467 Button: Add support to render link (for href)
  package-lock.json
  package.json
  src/components/Button/Button.css.js
  src/components/Button/ButtonV2.js
  src/components/Button/__tests__/ButtonV2.test.js
  src/components/Button/docs/ButtonV2.md
  stories/ButtonV2.stories.js
Labels: enhancement ✨

#468 Button: Add PrimaryAlt (purple) variant
  src/components/Button/Button.css.js
  src/components/Button/ButtonV2.js
  src/components/Button/docs/ButtonV2.md
  src/components/Button/types.js
  stories/ButtonV2.stories.js
Labels: enhancement ✨

#470 Button: Remove underline for link selector
  .groovyrc.json
  src/components/Button/Button.css.js
Labels: enhancement ✨

#471 Add color yellow to tag colors
  src/components/Tag/README.md
  src/components/Tag/Tag.css.ts
  src/components/Tag/Tag.tsx
  stories/Tag/Tag.stories.js
Labels: enhancement ✨

#473 Attachment: Adding Error state
  src/components/Attachment/Attachment.css.js
  src/components/Attachment/Attachment.tsx
  src/components/Attachment/__tests__/Attachment.test.js
  src/components/Attachment/docs/Attachment.md
  stories/Attachment.stories.js
  stories/AttachmentList.stories.js
Labels: enhancement ✨, refactor ♻️

#475 DropdownV2: Resolve item render updates
  src/components/AnimateGroup/__tests__/AnimateGroup.test.js
  src/components/Dropdown/V2/Dropdown.Container.tsx
  stories/DropdownV2.stories.js
Labels: bug 🐛

#472 Modal + Message.Media Modal updates
  src/components/Message/Media.js
  src/components/Message/__tests__/Media.test.js
  src/components/Message/docs/Media.md
  src/components/Message/styles/Media.css.js
  src/components/Modal/styles/Modal.css.js
  stories/Message/Message.Media.old.stories.js
  stories/Message/Message.Media.stories.js
Labels: enhancement ✨, refactor ♻️

#477 Attachment: Fix error link (hover) colour
  src/components/Attachment/Attachment.css.js
Labels: bug 🐛

#463 New Blue
  package-lock.json
  package.json
  src/components/ArticleCard/styles/ArticleCard.css.js
  src/components/CloseButton/CloseButton.css.js
  src/components/CopyButton/styles/CopyButton.css.js
  src/components/Highlight/styles/Highlight.css.js
  src/components/Message/styles/Action.css.js
  src/components/Message/styles/Bubble.css.js
  src/components/Message/styles/Embed.css.js
  src/components/Message/styles/Media.css.js
  src/components/PreviewCard/styles/PreviewCard.css.js
  src/components/Text/styles/Text.css.ts
  src/styles/configs/colors.ts
  src/styles/configs/constants.ts
  src/styles/utilities/color.ts
  src/styles/utilities/forEach.js
  src/styles/utilities/forEach.ts
  src/styles/utilities/theme.ts
  src/styles/utilities/variableFontSize.ts
Labels: enhancement ✨

#478 Storybook: Enhance with addons
  .storybook/addons.js
  .storybook/config.js
  package-lock.json
  package.json
Labels: enhancement ✨

#481 Fix progress bar docs
  src/components/ProgressBar/README.md
Labels: documentation 🖋

#482 Colours: Update shades of Blue for accessibility
  package-lock.json
  package.json
  src/components/ArticleCard/styles/ArticleCard.css.js
  src/components/Button/Button.css.js
  src/components/Dropdown/V2/Dropdown.css.js
  src/components/PreviewCard/styles/PreviewCard.css.js
  src/components/Text/styles/Text.css.ts
  src/styles/configs/_color.scss
  src/styles/configs/colors.ts
  src/styles/mixins/linkStyles.css.js
  src/styles/mixins/linkStyles.scss
Labels: enhancement ✨, high priority ⚠️

#484 Set up colorway for automatic color handling
  package-lock.json
  package.json
  src/styles/configs/_color.scss
  src/styles/configs/_colorway.scss
  src/styles/configs/colors.ts
  src/styles/configs/colorway.ts
Labels: enhancement ✨

#485 RateAction: Fix active circle sizing
  src/components/RateAction/RateAction.css.ts
Labels: bug 🐛

#487 Update the color of note chat message bubbles
  src/components/Message/styles/Bubble.css.js
  src/components/Message/styles/Embed.css.js
  src/components/Message/styles/Media.css.js
Labels: enhancement ✨

#480 Message.Media: Remove caption from modal
  src/components/Message/Media.js
Labels: enhancement ✨

#486 Add new Pagination component
  package-lock.json
  src/components/Pagination/Pagination.css.js
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/Pagination.utils.ts
  src/components/Pagination/README.md
  src/components/Pagination/__tests__/Pagination.test.js
  src/components/Pagination/index.ts
  src/components/index.js
  src/utilities/__tests__/pluralize.test.ts
  src/utilities/pluralize.ts
  stories/Pagination.stories.js
Labels: enhancement ✨, feature 💅

#490 Inline: Refactor
  .storybook/webpack.config.js
  package-lock.json
  src/components/Inline/Inline.Item.tsx
  src/components/Inline/Inline.css.ts
  src/components/Inline/Inline.tsx
  src/components/Inline/Inline.utils.ts
  src/components/Inline/Item.js
  src/components/Inline/README.md
  src/components/Inline/__tests__/Inline.Item.test.tsx
  src/components/Inline/__tests__/Inline.test.tsx
  src/components/Inline/docs/Inline.md
  src/components/Inline/docs/Item.md
  src/components/Inline/index.js
  src/components/Inline/index.ts
  src/components/Inline/propTypes.js
  src/components/Inline/tests/Inline.test.js
  src/components/Inline/tests/Item.test.js
  src/components/TagList/TagList.tsx
  src/styles/components/Inline/Inline.scss
  src/styles/components/Inline/InlineItem.scss
  src/styles/components/Inline/__index.scss
  stories/Inline.stories.js
  stories/TagList.stories.js
Labels: enhancement ✨, refactor ♻️

#489 Input: Add embedded Action
  package-lock.json
  src/components/Input/Input.js
  src/components/Input/Prefix.js
  src/components/Input/Suffix.js
  src/components/Input/__tests__/Input.test.js
  src/components/Input/__tests__/Suffix.test.js
  src/components/Input/docs/Input.md
  src/components/Input/styles/Input.css.js
  stories/Input.stories.js
Labels: enhancement ✨

#495 Speed up Storybook
  .gitignore
  .storybook/webpack.config.js
  .travis.yml
Labels: enhancement ✨

#493 Button/Links: Enhance with marionette + React routing support
  .gitignore
  package-lock.json
  package.json
  src/components/Button/ButtonV2.js
  src/components/Button/__tests__/ButtonV2.test.js
  src/components/RouteWrapper/__tests__/RouteWrapper.test.js
  src/components/RouteWrapper/index.js
  stories/ButtonV2.stories.js
Labels: enhancement ✨

#497 Replace async/await usage in Pop with Promise
  src/components/Pop/Pop.js
Labels: bug 🐛

#498 Add NavLink component
  package-lock.json
  package.json
  src/components/NavLink/NavLink.tsx
  src/components/NavLink/NavLink.utils.ts
  src/components/NavLink/README.md
  src/components/NavLink/__tests__/NavLink.test.tsx
  src/components/NavLink/index.ts
  src/components/index.js
  stories/NavLink.stories.js
Labels: enhancement ✨, feature 💅

#500 Input: Refactor Resizer/Static CSS
  .storybook/storybook.css
  src/components/Input/Resizer.css.ts
  src/components/Input/Resizer.tsx
  src/components/Input/Static.css.ts
  src/components/Input/Static.js
  src/components/Input/__tests__/Resizer.test.js
  src/styles/components/Input/InputGhost.scss
  src/styles/components/Input/InputResizer.scss
  src/styles/components/Input/InputStatic.scss
  src/styles/components/Input/InputWrapper.scss
  src/styles/components/Input/__index.scss
Labels: bug 🐛, enhancement ✨, refactor ♻️

#501 Add Stepper Component
  src/components/Stepper/README.md
  src/components/Stepper/Stepper.Progress.tsx
  src/components/Stepper/Stepper.Step.tsx
  src/components/Stepper/Stepper.css.ts
  src/components/Stepper/Stepper.tsx
  src/components/Stepper/Stepper.types.ts
  src/components/Stepper/Stepper.utils.ts
  src/components/Stepper/__tests__/Stepper.Step.test.tsx
  src/components/Stepper/__tests__/Stepper.test.tsx
  src/components/Stepper/index.ts
  src/components/index.js
  src/styles/includePaths.js
  stories/Stepper.stories.js
Labels: enhancement ✨, feature 💅

#502 Fix: Opening Autodropdown causes scroll to bottom
  src/components/Input/Input.js
  src/components/Input/__tests__/Input.test.js
  stories/AutoDropdown.stories.js
Labels: bug 🐛

#491 Add SplitButton component
  package-lock.json
  src/components/Button/Button.css.js
  src/components/Button/ButtonV2.js
  src/components/Button/__tests__/ButtonV2.test.js
  src/components/Dropdown/V2/Dropdown.Trigger.tsx
  src/components/Dropdown/V2/Dropdown.store.js
  src/components/Dropdown/V2/Dropdown.tsx
  src/components/Dropdown/V2/Dropdown.types.ts
  src/components/Dropdown/V2/__tests__/Dropdown.Trigger.test.tsx
  src/components/Dropdown/V2/docs/Dropdown.md
  src/components/SplitButton/SplitButton.css.ts
  src/components/SplitButton/SplitButton.md
  src/components/SplitButton/SplitButton.tsx
  src/components/SplitButton/SplitButton.utils.ts
  src/components/SplitButton/__tests__/SplitButton.test.tsx
  src/components/SplitButton/index.ts
  src/components/index.js
  stories/DropdownV2.stories.js
  stories/SplitButton.stories.js
Labels: feature 💅

#504 Fix appearance of disabled SplitButtons and SplitButtons with state
  src/components/SplitButton/SplitButton.css.ts
  src/components/SplitButton/SplitButton.tsx
  stories/SplitButton.stories.js
Labels: bug 🐛

#505 Temporarily disable data-bypass in links
  src/components/Button/ButtonV2.js
  src/components/RouteWrapper/__tests__/RouteWrapper.test.js
  src/components/RouteWrapper/index.js
Labels: bug 🐛

#508 DropdownV2: Better menu repositioning
  jest.config.js
  package-lock.json
  package.json
  src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
  src/components/Dropdown/V2/Dropdown.Trigger.tsx
  src/components/Dropdown/V2/Dropdown.actionTypes.ts
  src/components/Dropdown/V2/Dropdown.actions.ts
  src/components/Dropdown/V2/Dropdown.css.js
  src/components/Dropdown/V2/Dropdown.store.js
  src/components/Dropdown/V2/Dropdown.tsx
  src/components/Dropdown/V2/Dropdown.types.ts
  src/components/Dropdown/V2/__tests__/Dropdown.MenuContainer.test.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.Trigger.test.tsx
  src/components/Dropdown/V2/docs/Dropdown.md
  src/components/Portal/Portal.js
  src/components/SplitButton/SplitButton.tsx
  src/utilities/__tests__/memoize.test.ts
  src/utilities/env.ts
  src/utilities/memoize.ts
  stories/DropdownV2.stories.js
  stories/SplitButton.stories.js
Labels: bug 🐛, enhancement ✨, stability 💪
