Repository helpscout/hsds-react, pull requests merged in 2019-08, with the labels that each got.

#672 Updates some npm packages to fix linting and vulnerabilities
  .storybook/.babelrc
  babel.config.js
  package-lock.json
  package.json
Labels: stability 💪

#674 Fixes the IntersectionObserver guard for Safari 10, others
  src/components/Page/Page.StickyActions.tsx
  src/components/Page/Page.utils.ts
Labels: bug 🐛, hot fix 🔥

#677 Editable Fields Refactor
  .vscode/settings.json
  src/components/EditableField/EditableField.Actions.tsx
  src/components/EditableField/EditableField.Input.tsx
  src/components/EditableField/EditableField.Mask.tsx
  src/components/EditableField/EditableField.Truncate.tsx
  src/components/EditableField/EditableField.Truncated.tsx
  src/components/EditableField/EditableField.tsx
  src/components/EditableField/EditableField.types.ts
  src/components/EditableField/EditableField.utils.ts
  src/components/EditableField/README.md
  src/components/EditableField/__tests__/EditableField.Actions.test.tsx
  src/components/EditableField/__tests__/EditableField.Input.test.tsx
  src/components/EditableField/__tests__/EditableField.Mask.test.tsx
  src/components/EditableField/__tests__/EditableField.test.tsx
  src/components/EditableField/__tests__/EditableField.truncate.test.tsx
  src/components/EditableField/__tests__/EditableField.truncated.test.tsx
  src/components/EditableField/styles/EditableField.Actions.css.ts
  src/components/EditableField/styles/EditableField.Input.css.ts
  src/components/EditableField/styles/EditableField.Mask.css.ts
  src/components/EditableField/styles/EditableField.Truncate.css.ts
  src/components/EditableField/styles/EditableField.Truncated.css.ts
  src/components/EditableField/styles/EditableField.css.ts
  stories/EditableField.stories.js
Labels: enhancement ✨, refactor ♻️

#682 Truncated Button text
  src/components/MessageCard/styles/MessageCard.css.ts
Labels: bug 🐛, patch ☝️

#684 Fix: Inline FilteredList
  src/components/FilteredList/FilteredList.tsx
  src/components/FilteredList/__tests__/FilteredList.test.js
  stories/FilteredList.stories.js
Labels: bug 🐛

#685 Add Avatar action overlay
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/README.md
  src/components/Avatar/__tests__/Avatar.test.js
  src/components/Avatar/styles/Avatar.css.ts
  stories/Avatar/Avatar.stories.js
Labels: enhancement ✨

#691 Fix Avatar background color & Add remove avatar animation
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/README.md
  src/components/Avatar/__tests__/Avatar.test.js
  src/components/Avatar/styles/Avatar.css.ts
  stories/Avatar/Avatar.stories.js
Labels: bug 🐛, enhancement ✨, minor ✌️
