Repository helpscout/hsds-react, pull requests merged in 2019-04, with the labels that each got.

#554 HS App: Fix import for HsApp.css.js
  src/components/HsApp/HsApp.css.js
Labels: bug 🐛

#552 Tag: Close icon fix
  src/components/Icon/icons.all.js
  src/components/Icon/icons.embed.js
  stories/Toolbar.stories.js
Labels: bug 🐛, patch ☝️

#553 Fix the padding of chat preview cards
  src/components/PreviewCard/styles/PreviewCard.css.js
  src/styles/mixins/cardStyles.css.js
  src/styles/mixins/noteStyles.css.js
  stories/Message/Message.stories.js
Labels: enhancement ✨, patch ☝️

#556 Button: Add new size and state to V2
  src/components/Button/Button.css.js
  src/components/Button/types.js
  stories/ButtonV2.stories.js
Labels: enhancement ✨, minor ✌️

#557 Icon: Fix rendering sizes within Input and OptionIcon
  src/components/Input/Input.js
  src/components/OptionIcon/OptionIcon.js
Labels: bug 🐛, patch ☝️

#560 Button V2: Remove outline for hover, active, focus
  src/components/Button/Button.css.js
Labels: bug 🐛, patch ☝️

#562 Clean up ArticleCard UI
  src/components/ArticleCard/styles/ArticleCard.css.js
Labels: enhancement ✨, patch ☝️

#561 Icon: Adjust caret sizing + alignment
  src/components/Icon/styles/Icon.css.js
  stories/Icon.stories.js
Labels: bug 🐛, patch ☝️

#563 Blank slate component
  package-lock.json
  src/components/BlankSlate/BlankSlate.css.js
  src/components/BlankSlate/BlankSlate.tsx
  src/components/BlankSlate/README.md
  src/components/BlankSlate/__tests__/BlankSlate.test.tsx
  src/components/BlankSlate/index.ts
  src/components/BlankSlate/utils.ts
  src/components/index.js
  stories/BlankSlate.stories.js
Labels: feature 💅, minor ✌️

#566 Improve pagination component
  src/components/KeypressListener/__tests__/KeypressListener.test.js
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/__tests__/Pagination.test.js
  src/utilities/__tests__/number.test.js
  src/utilities/number.js
  stories/Pagination.stories.js
Labels: enhancement ✨, minor ✌️

#565 Remove VSCode Settings
  .vscode/settings.json
Labels: enhancement ✨

#550 Esc Stack: Add support for Modals, Dropdowns, Tooltips, and Popovers
  config/jsdomPolyfills.js
  src/components/ComboBox/ComboBox.tsx
  src/components/ComboBox/__tests__/ComboBox.test.tsx
  src/components/Dropdown/Menu.js
  src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
  src/components/Dropdown/V2/Dropdown.MenuPortal.tsx
  src/components/Dropdown/V2/Dropdown.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.MenuContainer.test.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.MenuPortal.test.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.test.tsx
  src/components/Dropdown/V2/__tests__/DropdownV2.test.tsx
  src/components/KeypressListener/__tests__/KeypressListener.test.js
  src/components/Modal/Modal.js
  src/components/Pop/Arrow.js
  src/components/Pop/Pop.Portal.tsx
  src/components/Pop/Pop.js
  src/components/Pop/Popper.js
  src/components/Pop/__tests__/Arrow.test.js
  src/components/Pop/__tests__/Pop.Portal.test.tsx
  src/components/Pop/__tests__/Pop.test.js
  src/components/Pop/__tests__/Popper.test.js
  src/components/Popper/Popper.js
  src/components/PortalWrapper/PortalWrapper.js
  src/components/Tooltip/__tests__/Tooltip.test.js
  stories/Modal.stories.js
Labels: bug 🐛, minor ✌️

#569 Add new spot-misc-empty illustration
  src/components/BlankSlate/BlankSlate.css.js
  src/components/BlankSlate/BlankSlate.tsx
  src/components/BlankSlate/__tests__/BlankSlate.test.tsx
  src/components/Illo/illos.all.js
  src/components/Illo/styles/Illo.css.js
  src/components/Illo/types.js
  src/illos/spot-misc-empty.svg
  stories/BlankSlate.stories.js
Labels: enhancement ✨, minor ✌️

#514 Feature/table
  .eslintignore
  .gitignore
  package-lock.json
  src/components/Table/Cell.tsx
  src/components/Table/HeaderCell.tsx
  src/components/Table/README.md
  src/components/Table/Row.tsx
  src/components/Table/Table.tsx
  src/components/Table/Table.utils.ts
  src/components/Table/__tests__/Table.test.js
  src/components/Table/__tests__/utils.js
  src/components/Table/docs/Columns.md
  src/components/Table/docs/Themes.md
  src/components/Table/index.ts
  src/components/Table/styles/Table.css.js
  src/components/Table/styles/themes.js
  src/components/Table/types.ts
  src/components/index.js
  stories/Table/ColumnsCustomizer.js
  stories/Table/Table.stories.js
  stories/Table/TableCustomizer.js
  stories/Table/TablePlayground.js
  stories/Table/TableWithPagination.js
  stories/Table/TableWithSorting.js
  stories/Table/commonComponents.js
Labels: feature 💅, minor ✌️

#577 Storybook: Lock React Treebeard at v3.1.0
  package-lock.json
  package.json
Labels: stability 💪

#567 TabBar component
  src/components/Nav/Nav.css.ts
  src/components/TabBar/README.md
  src/components/TabBar/TabBar.css.ts
  src/components/TabBar/TabBar.tsx
  src/components/TabBar/TabBar.utils.ts
  src/components/TabBar/__tests__/TabBar.test.tsx
  src/components/TabBar/docs/TabBar.md
  src/components/TabBar/index.ts
  src/components/index.js
  stories/TabBar.stories.js
Labels: feature 💅, minor ✌️

#574 Updated GreeterCard Styles
  src/components/GreeterCard/GreeterCard.css.ts
  src/components/GreeterCard/GreeterCard.tsx
Labels: bug 🐛, patch ☝️

#573 Input: Fix multiline size calculations + add default maxHeight
  src/components/Input/Input.js
  src/components/Input/Resizer.tsx
  src/components/Input/__tests__/Input.test.js
Labels: bug 🐛, enhancement ✨, minor ✌️

#583 Fix smoothScrollTo function to work in IE/Edge
  src/utilities/smoothScroll.js
Labels: bug 🐛, patch ☝️

#584 HsApp: Remove helix dependency
  package-lock.json
  package.json
  src/components/HsApp/HsApp.tsx
  src/components/HsApp/Nav.tsx
  src/utilities/pkg.ts
  stories/HsApp.stories.js
Labels: bug 🐛, patch ☝️

#578 Add Cypress tests for Pagination component
  cypress/integration/Pagination.js
  cypress/support/commands.js
  src/components/Pagination/Pagination.css.js
  src/components/Pagination/Pagination.tsx
  stories/Pagination.stories.js
Labels: enhancement ✨, patch ☝️

#576 Heading: Add wordWrap (and other props from Text)
  src/components/Heading/Heading.css.ts
  src/components/Heading/Heading.tsx
  src/components/Heading/README.md
  src/components/Heading/__tests__/Heading.test.tsx
  src/components/Text/README.md
  stories/Heading.stories.js
  stories/Heading.stories.tsx
Labels: enhancement ✨, patch ☝️

#582 Avatar: Render fix for Safari (Mac/iOS)
  .storybook/preview-head.html
  src/components/Avatar/Avatar.Crop.tsx
  src/components/Avatar/Avatar.Image.tsx
  src/components/Avatar/Avatar.css.ts
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/__tests__/Avatar.test.js
  stories/AvatarStackV2.stories.js
Labels: bug 🐛, patch ☝️

#587 ScrollLock: Locking fix + resolve console warning
  config/jest/setupTests.js
  package-lock.json
  package.json
  src/components/ScrollLock/ScrollLock.tsx
  src/components/ScrollLock/__tests__/ScrollLock.test.js
Labels: bug 🐛, patch ☝️

#579 Spinner: Update UI + Add isLoading to Button (V2)
  src/components/Button/Button.css.js
  src/components/Button/ButtonV2.js
  src/components/Button/__tests__/ButtonV2.test.js
  src/components/Button/docs/ButtonV2.md
  src/components/Spinner/README.md
  src/components/Spinner/Spinner.css.ts
  src/components/Spinner/Spinner.tsx
  src/components/Spinner/Spinner.types.ts
  src/components/Spinner/Spinner.utils.ts
  src/components/Spinner/__tests__/Spinner.test.tsx
  src/components/Spinner/index.js
  src/components/Spinner/index.ts
  src/components/Spinner/propTypes.js
  src/components/Spinner/tests/Spinner.test.js
  src/styles/components/Spinner.scss
  stories/ButtonV2.stories.js
Labels: enhancement ✨, feature 💅, minor ✌️, refactor ♻️

#590 Improve auto linking to allow longer TLDs
  src/utilities/__tests__/strings.test.js
  src/utilities/strings.ts
Labels: enhancement ✨, patch ☝️

#592 Avatars: Make shape default to circles
  package-lock.json
  package.json
  src/components/AvatarGrid/AvatarGrid.js
  src/components/Message/Message.js
  src/components/Message/__tests__/Message.test.js
  src/components/StatusAvatar/StatusAvatar.js
  src/utilities/pkg.ts
Labels: enhancement ✨, minor ✌️

#494 SideNavigation component
  .vscode/launch.json
  src/components/Button/Button.css.js
  src/components/HsApp/Sidenav.tsx
  src/components/HsApp/__tests__/Sidenav.test.js
  src/components/Icon/styles/Icon.css.js
  src/components/Icon/types.js
  src/components/SideNavigation/Button.tsx
  src/components/SideNavigation/DropdownFooter.tsx
  src/components/SideNavigation/DropdownHeader.tsx
  src/components/SideNavigation/FadeInOut.tsx
  src/components/SideNavigation/Footer.tsx
  src/components/SideNavigation/Header.tsx
  src/components/SideNavigation/Heading.tsx
  src/components/SideNavigation/Item.tsx
  src/components/SideNavigation/README.md
  src/components/SideNavigation/Section.tsx
  src/components/SideNavigation/SideNavigation.css.js
  src/components/SideNavigation/SideNavigation.tsx
  src/components/SideNavigation/SideNavigation.utils.ts
  src/components/SideNavigation/__tests__/SideNavigation.Button.test.js
  src/components/SideNavigation/__tests__/SideNavigation.DropdownFooter.test.js
  src/components/SideNavigation/__tests__/SideNavigation.DropdownHeader.test.js
  src/components/SideNavigation/__tests__/SideNavigation.FadeInOut.test.js
  src/components/SideNavigation/__tests__/SideNavigation.Footer.test.js
  src/components/SideNavigation/__tests__/SideNavigation.Header.test.js
  src/components/SideNavigation/__tests__/SideNavigation.Item.test.js
  src/components/SideNavigation/__tests__/SideNavigation.Section.test.js
  src/components/SideNavigation/__tests__/SideNavigation.test.js
  src/components/SideNavigation/docs/Button.md
  src/components/SideNavigation/docs/DropdownFooter.md
  src/components/SideNavigation/docs/DropdownHeader.md
  src/components/SideNavigation/docs/Footer.md
  src/components/SideNavigation/docs/Header.md
  src/components/SideNavigation/docs/Heading.md
  src/components/SideNavigation/docs/Item.md
  src/components/SideNavigation/docs/Section.md
  src/components/SideNavigation/index.ts
  src/components/index.js
  stories/DropdownV2.stories.js
  stories/SideNavigation.stories.js
Labels: feature 💅, minor ✌️

#591 Upgrades storybook to v5
  .storybook/addons.js
  .storybook/config.js
  .storybook/webpack.config.js
  package-lock.json
  package.json
Labels: enhancement ✨, minor ✌️, tooling :wrench:

#594 Upgrades Jest to v24
  .babelrc
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
Labels: enhancement ✨, tooling :wrench:

#580 Dropdown V2: Add Multi-select support
  src/components/ComboBox/ComboBox.tsx
  src/components/Dropdown/V2/Dropdown.Container.tsx
  src/components/Dropdown/V2/Dropdown.Item.tsx
  src/components/Dropdown/V2/Dropdown.ItemSelectedCheck.tsx
  src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
  src/components/Dropdown/V2/Dropdown.Renderer.tsx
  src/components/Dropdown/V2/Dropdown.actionTypes.ts
  src/components/Dropdown/V2/Dropdown.actions.ts
  src/components/Dropdown/V2/Dropdown.css.js
  src/components/Dropdown/V2/Dropdown.reducer.ts
  src/components/Dropdown/V2/Dropdown.tsx
  src/components/Dropdown/V2/Dropdown.types.ts
  src/components/Dropdown/V2/Dropdown.utils.ts
  src/components/Dropdown/V2/__tests__/Dropdown.Item.test.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.MenuContainer.test.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.actions.test.ts
  src/components/Dropdown/V2/__tests__/Dropdown.reducer.test.ts
  src/components/Dropdown/V2/__tests__/Dropdown.utils.test.tsx
  src/components/Dropdown/V2/docs/Dropdown.md
  stories/AutoDropdown.stories.js
  stories/ComboBox.stories.js
  stories/DropdownV2.stories.js
Labels: enhancement ✨, minor ✌️

#589 Improve Tag UI. Add tag size, tag new color and a TagList clear all button
  src/components/Tag/README.md
  src/components/Tag/Tag.css.ts
  src/components/Tag/Tag.tsx
  src/components/Tag/__tests__/Tag.test.js
  src/components/TagList/README.md
  src/components/TagList/TagList.css.ts
  src/components/TagList/TagList.tsx
  src/components/TagList/__tests__/TagList.test.js
  stories/Tag/Tag.stories.js
  stories/TagList.stories.js
Labels: enhancement ✨, minor ✌️

#593 Refactor input error-state outline color to Red
  src/components/Input/BackdropV2.js
  src/components/Input/__tests__/BackdropV2.test.js
  src/components/Input/styles/BackdropV2.css.js
  src/components/Input/utils.js
Labels: enhancement ✨, patch ☝️

#597 Data Cy: Unwrap Namespaces
  src/components/PropProvider/propConnect.tsx
  src/utilities/__tests__/component.test.js
  src/utilities/component.ts
Labels: bug 🐛, patch ☝️

#598 Pagination - hide range if number of pages < 2
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/__tests__/Pagination.test.js
Labels: enhancement ✨, minor ✌️

#600 Page.Card: Add additional bottom margin
  src/components/Page/styles/Card.css.ts
Labels: enhancement ✨, minor ✌️

#603 Dropdown: Fix label rendering in multi select
  src/components/Dropdown/V2/Dropdown.ItemSelectedCheck.tsx
Labels: bug 🐛, patch ☝️

#605 Dropdown: Multi-select: Match active item (without id)
  src/components/Dropdown/V2/Dropdown.Renderer.tsx
  stories/AutoDropdown.stories.js
Labels: bug 🐛, patch ☝️

#604 Input: Improve state focus ring colours
  src/components/Input/BackdropV2.tsx
  src/components/Input/Input.js
  src/components/Input/styles/BackdropV2.css.ts
  src/components/Input/utils.js
  src/constants/types.js
  src/constants/types.ts
  stories/Input.stories.js
Labels: enhancement ✨, minor ✌️

#585 Route: Fork react-router/Route to remove dependency
  jest.config.js
  package-lock.json
  package.json
  src/components/NavLink/NavLink.tsx
  src/components/Popper/README.md
  src/components/Route/README.md
  src/components/Route/Route.js
  src/components/Route/index.ts
  src/components/index.js
  src/utilities/component.ts
  src/utilities/react-router/matchPath.js
Labels: enhancement ✨, minor ✌️

#607 Cyan: Add Modal + Input integration tests
  package-lock.json
  package.json
  src/components/Input/__tests__/Input.integration.test.js
  src/components/Modal/__tests__/Modal.integration.test.js
  src/utilities/clipboard.js
Labels: enhancement ✨, stability 💪

#608 Avatar: Remove background when image is loaded
  src/components/Avatar/Avatar.Crop.tsx
  src/components/Avatar/Avatar.tsx
  stories/Avatar/AvatarV2.stories.js
Labels: bug 🐛, patch ☝️
