Repository helpscout/hsds-react, pull requests merged in 2019-05, with the labels that each got.

#610 Remove unicode modifier from auto linking regex
  src/utilities/strings.ts
Labels: bug 🐛

#602 Enhancement/table updates
  src/components/Scrollable/README.md
  src/components/Scrollable/Scrollable.tsx
  src/components/Table/README.md
  src/components/Table/Table.tsx
  src/components/Table/Table.utils.ts
  src/components/Table/__tests__/Table.test.js
  src/components/Table/styles/Table.css.js
  src/components/Table/types.ts
  stories/Table/TablePlayground.js
Labels: bug 🐛, enhancement ✨, patch ☝️

#615 Reduce size of the auto link regex
  src/utilities/__tests__/strings.test.js
  src/utilities/strings.ts
Labels: patch ☝️

#606 RouteWrapper: Add basename (path) to rendered "to" href
  src/components/RouteWrapper/RouteWrapper.tsx
  src/components/RouteWrapper/__tests__/RouteWrapper.integration.test.js
  src/components/RouteWrapper/__tests__/RouteWrapper.test.js
  src/utilities/__tests__/history.test.ts
  src/utilities/history.ts
  stories/NavLink.stories.js
Labels: bug 🐛, patch ☝️

#612 Add IconButton Component
  .remake/component/remake-name/__tests__/remake-name.test.tsx
  .remake/component/remake-name/remake-name.tsx
  .remake/story/remake-name.stories.js
  package-lock.json
  package.json
  src/components/Button/Button.tsx
  src/components/Button/Button.types.ts
  src/components/Button/ButtonV2.tsx
  src/components/Button/index.tsx
  src/components/Button/styles/Button.css.js
  src/components/CopyButton/CopyButton.tsx
  src/components/IconButton/IconButton.tsx
  src/components/IconButton/IconButton.utils.ts
  src/components/IconButton/README.md
  src/components/IconButton/__tests__/IconButton.test.tsx
  src/components/IconButton/index.ts
  src/components/IconButton/styles/IconButton.css.ts
  src/components/index.ts
  stories/IconButton.stories.js
Labels: enhancement ✨, feature 💅, minor ✌️, refactor ♻️

#611 Accordion: Body Overflow Fix
  src/components/Accordion/styles/Accordion.css.ts
  src/components/Collapsible/Collapsible.tsx
  src/components/Collapsible/styles/Collapsible.css.ts
  src/styles/components/Collapsible.scss
Labels: enhancement ✨, patch ☝️

#619 Remake: Template updates
  .remake/component/remake-name/remake-name.css.ts
  .remake/component/remake-name/remake-name.tsx
  .remake/component/remake-name/remake-name.types.ts
  .remake/component/remake-name/styles/remake-name.css.ts
  package-lock.json
  package.json
Labels: enhancement ✨, tooling :wrench:

#624 Pop (Tooltip/Popover): Fix closeOnBodyClick
  src/components/EventListener/EventListener.tsx
  src/components/Pop/Arrow.tsx
  src/components/Pop/Pop.tsx
  src/components/Pop/Pop.types.ts
  src/components/Pop/Pop.utils.ts
  src/components/Pop/Popper.tsx
  src/components/Pop/README.md
  src/components/Pop/docs/Pop.md
  src/components/Popover/Popover.tsx
  src/components/Popover/__tests__/Popover.integration.test.tsx
  src/components/Tooltip/Tooltip.tsx
Labels: bug 🐛, enhancement ✨, refactor ♻️

#625 Page: Adjust margins
  src/components/FormGroup/styles/Choice.css.ts
  src/components/FormGroup/styles/FormGroup.css.ts
  src/components/Page/styles/Page.Card.css.ts
  stories/Page/Page.Example.stories.js
Labels: enhancement ✨, patch ☝️

#627 ActionSelect: Fix resize and refocus interactions
  package-lock.json
  package.json
  src/components/ActionSelect/ActionSelect.ContentResizer.tsx
  src/components/ActionSelect/ActionSelect.tsx
  src/components/ActionSelect/ActionSelect.types.ts
  src/components/ActionSelect/__tests__/ActionSelect.test.tsx
  src/components/Choice/Choice.tsx
  src/components/Choice/Choice.types.ts
  src/components/Choice/__tests__/Choice.test.js
  src/components/Choice/styles/Choice.css.js
  src/components/Dropdown/V2/Dropdown.Trigger.tsx
  src/components/Dropdown/V2/Dropdown.actions.ts
  src/components/Message/__tests__/Message.integration.test.js
  src/components/Pop/Pop.tsx
  src/components/Pop/__tests__/Pop.test.js
  src/utilities/focus.ts
  src/utilities/node.ts
  src/utilities/pkg.ts
  stories/ActionSelect.stories.js
Labels: bug 🐛, enhancement ✨, patch ☝️, refactor ♻️

#628 Page.Action: Add guard for IntersectionObserver
  src/components/Page/Page.Actions.tsx
  src/components/Page/Page.StickyActions.tsx
Labels: bug 🐛, patch ☝️, stability 💪

#630 ActionSelect: Improve UX by coordinating focus + scrolling
  src/components/ActionSelect/ActionSelect.ContentResizer.tsx
  src/components/ActionSelect/ActionSelect.tsx
  src/components/ActionSelect/ActionSelect.types.ts
  src/components/ActionSelect/README.md
  src/utilities/smoothScroll.ts
  stories/ActionSelect.QA.stories.js
  stories/ActionSelect.stories.js
Labels: enhancement ✨, patch ☝️

#631 ActionSelect: Improve the scrollIntoView callback props
  .flowconfig
  package-lock.json
  package.json
  src/components/ActionSelect/ActionSelect.tsx
  src/components/Dropdown/V2/Dropdown.css.js
  stories/ActionSelect.stories.js
Labels: enhancement ✨, patch ☝️

#633 Enhance storybook environment
  .remake/story/remake-name.stories.js
  .storybook/addons.js
  .storybook/config.js
  .storybook/webpack.config.js
  package-lock.json
  package.json
  stories/DropdownV2.stories.js
Labels: documentation 🖋, tooling :wrench:

#632 GreeterRow: Fix link clicks
  src/components/Accordion/Accordion.Title.tsx
  src/components/Accordion/Accordion.types.ts
  src/components/Accordion/__tests__/Accordion.Title.test.js
Labels: bug 🐛, patch ☝️

#634 ActionSelect: Scroll into view if needed
  package-lock.json
  package.json
  src/components/ActionSelect/ActionSelect.tsx
  src/utilities/pkg.ts
Labels: enhancement ✨, patch ☝️

#636 Multi select dropdown alignment
  src/components/Dropdown/V2/Dropdown.ItemSelectedCheck.tsx
  src/components/Dropdown/V2/Dropdown.css.js
  stories/DropdownV2.stories.js
Labels: enhancement ✨

#635 Improve table performance
  package-lock.json
  package.json
  src/components/Table/Table.Body.tsx
  src/components/Table/Table.Head.tsx
  src/components/Table/Table.tsx
  src/components/Table/Table.types.ts
  src/components/Table/__tests__/Table.test.js
  src/components/Table/styles/Table.css.js
  src/utilities/pkg.ts
Labels: enhancement ✨, minor ✌️

#639 Pagination - Hide next & last button on last page
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/__tests__/Pagination.test.js
Labels: enhancement ✨
