Repository helpscout/hsds-react, pull requests merged in 2019-01, with the labels that each got.

#438 propConnect: Add wrappedRef
  src/components/PropProvider/__tests__/propConnect.test.js
  src/components/PropProvider/docs/propConnect.md
  src/components/PropProvider/propConnect.tsx
Labels: enhancement ✨

#439 ChatScroller: Fix reference for scrollableNode
  src/components/ChatScroller/ChatScroller.tsx
  src/components/ChatScroller/README.md
  src/components/ChatScroller/__tests__/ChatScroller.test.js
Labels: bug 🐛, high priority ⚠️

#440 ChatScroller: Re-add ability to target an outer selector
  src/components/ChatScroller/ChatScroller.tsx
  stories/ChatScroller.stories.js
Labels: bug 🐛

#441 ChatScroller: Fix scrollableSelector for iFrames + add force prop
  package-lock.json
  package.json
  src/components/ChatScroller/ChatScroller.tsx
  src/components/ChatScroller/README.md
  src/components/ChatScroller/__tests__/ChatScroller.test.js
Labels: bug 🐛, enhancement ✨

#442 Update Fancy + React Utils
  package-lock.json
  package.json
Labels: enhancement ✨

#443 Input: Reduce suffix error icon margin
  src/components/Input/styles/Input.css.js
Labels: bug 🐛

#444 Select: Adjust error icon alignment
  package-lock.json
  package.json
  src/components/Select/Select.css.ts
Labels: bug 🐛

#445 ChatScroller: Reset Nodes
  package-lock.json
  package.json
  src/components/ChatScroller/ChatScroller.tsx
  src/components/ChatScroller/__tests__/ChatScroller.test.js
Labels: enhancement ✨

#446 SelectDropdown: Add support for value
  package-lock.json
  package.json
  src/components/Dropdown/V2/Dropdown.Trigger.tsx
  src/components/Dropdown/V2/Dropdown.store.js
  src/components/Dropdown/V2/Dropdown.types.ts
  src/components/Dropdown/V2/docs/Dropdown.md
  src/components/SelectDropdown/README.md
  src/components/SelectDropdown/SelectDropdown.css.ts
  src/components/SelectDropdown/SelectDropdown.tsx
  src/components/SelectDropdown/__tests__/SelectDropdown.test.tsx
  src/utilities/__tests__/arrays.test.js
  src/utilities/arrays.ts
  stories/SelectDropdown.stories.js
Labels: bug 🐛, enhancement ✨

#447 Input: Resizer - Recalculate height on mount
  src/components/Input/Resizer.tsx
  src/components/Input/__tests__/Resizer.test.js
Labels: enhancement ✨

#448 Tag/TagList: Add onBeforeRemove feature + refactor
  src/components/Centralize/Centralize.css.ts
  src/components/Centralize/Centralize.js
  src/components/Centralize/Centralize.tsx
  src/components/Centralize/Centralize.utils.ts
  src/components/Centralize/README.md
  src/components/Centralize/__tests__/Centralize.test.js
  src/components/Centralize/index.js
  src/components/Centralize/index.ts
  src/components/Centralize/styles/Centralize.css.js
  src/components/Tag/README.md
  src/components/Tag/Tag.css.ts
  src/components/Tag/Tag.js
  src/components/Tag/Tag.tsx
  src/components/Tag/Tag.utils.ts
  src/components/Tag/__tests__/Tag.test.js
  src/components/Tag/index.js
  src/components/Tag/index.ts
  src/components/TagList/README.md
  src/components/TagList/TagList.css.ts
  src/components/TagList/TagList.js
  src/components/TagList/TagList.tsx
  src/components/TagList/TagList.utils.ts
  src/components/TagList/__tests__/TagList.test.js
  src/components/TagList/index.js
  src/components/TagList/index.ts
  src/components/TagList/styles/TagList.css.js
  src/utilities/__tests__/other.test.js
  src/utilities/other.ts
  stories/SelectDropdown.stories.js
  stories/Tag/Tag.stories.js
  stories/TagList.stories.js
Labels: enhancement ✨, feature 💅, refactor ♻️

#450 Input/Select: Firefox text/selection fixes
  package-lock.json
  package.json
  src/components/Input/styles/Input.css.js
  src/components/Select/Select.css.ts
Labels: bug 🐛

#451 AvatarStack: Adjust UI + Update Storybook
  src/components/Animate/styles/sequences/index.css.js
  src/components/Animate/styles/sequences/left.css.js
  src/components/AvatarStack/AvatarStack.css.ts
  src/components/AvatarStack/AvatarStack.tsx
  src/components/AvatarStack/AvatarStack.utils.ts
  src/components/AvatarStack/AvatarStackV2.js
  src/components/AvatarStack/AvatarStackV2.tsx
  src/components/AvatarStack/README.md
  src/components/AvatarStack/__tests__/AvatarStack.test.js
  src/components/AvatarStack/__tests__/AvatarStackV2.test.js
  src/components/AvatarStack/index.js
  src/components/AvatarStack/index.ts
  stories/AvatarStackV2.stories.js
Labels: enhancement ✨, refactor ♻️

#452 Avatar: Adjust XL size + refactor
  src/components/Avatar/Avatar.css.ts
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/Avatar.types.ts
  src/components/Avatar/Avatar.utils.ts
  src/components/Avatar/AvatarV2.tsx
  src/components/Avatar/__tests__/Avatar.test.js
  src/components/Avatar/__tests__/AvatarV2.test.js
  src/components/Avatar/index.tsx
  src/components/Avatar/types.js
  src/components/Avatar/utils.js
  src/components/AvatarGrid/AvatarGrid.js
  src/components/AvatarList/AvatarList.tsx
  src/components/AvatarStack/AvatarStack.tsx
  src/components/Skeleton/styles/Avatar.css.js
  stories/Avatar/Avatar.stories.js
  stories/Avatar/AvatarV2.js
  stories/Avatar/AvatarV2.stories.js
  stories/AvatarStackV2.stories.js
Labels: enhancement ✨, refactor ♻️

#456 Fix carriage returns
  src/components/Input/Input.js
  src/components/Input/__tests__/Input.test.js
  src/components/Input/docs/Input.md
  stories/Input.stories.js
Labels: enhancement ✨

#457 Fix carriage returns (Tests)
  src/components/Input/Input.js
  src/components/Input/__tests__/Input.test.js
Labels: bug 🐛

#458 Enable Programmatic Control of Accordion Sections
  src/components/Accordion/Accordion.js
  src/components/Accordion/Section.js
  src/components/Accordion/__tests__/Accordion.test.js
  src/components/Accordion/__tests__/Section.test.js
  src/components/Accordion/docs/Accordion.md
  src/components/Accordion/docs/Section.md
  src/components/Accordion/types.js
  stories/Accordion.stories.js
Labels: enhancement ✨

#460 Fix carriage returns: Modifier keys
  src/utilities/__tests__/keys.test.ts
  src/utilities/keys.ts
Labels: enhancement ✨

#461 Don't render Toolbar Item/Block without any children
  src/components/Toolbar/Block.js
  src/components/Toolbar/Item.js
  src/components/Toolbar/tests/Block.test.js
  src/components/Toolbar/tests/Item.test.js
Labels: enhancement ✨

#464 Fixes inserting empty return if there is no value in field
  src/components/Input/Input.js
  src/components/Input/__tests__/Input.test.js
Labels: enhancement ✨
