Repository helpscout/hsds-react, pull requests merged in 2019-07, with the labels that each got.

#652 New Filtered List component && StatusBadge update
  src/components/Badge/styles/Badge.css.js
  src/components/FilteredList/FilteredList.tsx
  src/components/FilteredList/FilteredList.utils.ts
  src/components/FilteredList/README.md
  src/components/FilteredList/__tests__/FilteredList.test.js
  src/components/FilteredList/index.ts
  src/components/FilteredList/styles/FilteredList.css.js
  src/components/index.ts
  stories/Badge.stories.js
  stories/FilteredList.stories.js
Labels: feature 💅, minor ✌️

#656 Emoji picker styling updates
  src/components/EmojiPicker/EmojiPicker.tsx
  src/components/EmojiPicker/styles/EmojiPicker.css.ts
  stories/EmojiPicker.stories.js
Labels: bug 🐛, minor ✌️

#657 Refactor EmojiPicker active/hover state styling
  src/components/EmojiPicker/styles/EmojiPicker.css.ts
Labels: enhancement ✨, minor ✌️

#659 Remove EmojiPicker hover state transition
  src/components/EmojiPicker/styles/EmojiPicker.css.ts
Labels: enhancement ✨, patch ☝️

#662 Support Custom Illos in BlankSlate Component
  .npmrc
  package-lock.json
  package.json
  src/components/ActionSelect/ActionSelect.ContentResizer.tsx
  src/components/ActionSelect/ActionSelect.tsx
  src/components/ActionSelect/__tests__/ActionSelect.test.tsx
  src/components/Animate/__tests__/Animate.test.js
  src/components/AnimateGroup/AnimateGroup.tsx
  src/components/BlankSlate/BlankSlate.tsx
  src/components/BlankSlate/README.md
  src/components/BlankSlate/__tests__/BlankSlate.test.tsx
  src/components/BlankSlate/styles/BlankSlate.css.js
  src/components/Page/Page.StickyActions.tsx
  stories/BlankSlate.stories.js
Labels: enhancement ✨, minor ✌️

#643 Editable Input Fields
  package-lock.json
  package.json
  src/components/EditableField/EditableField.Input.tsx
  src/components/EditableField/EditableField.Truncate.tsx
  src/components/EditableField/EditableField.tsx
  src/components/EditableField/EditableField.types.ts
  src/components/EditableField/EditableField.utils.ts
  src/components/EditableField/README.md
  src/components/EditableField/__tests__/EditableField.Input.test.tsx
  src/components/EditableField/__tests__/EditableField.test.tsx
  src/components/EditableField/__tests__/EditableField.truncate.test.tsx
  src/components/EditableField/index.ts
  src/components/EditableField/styles/EditableField.Input.css.ts
  src/components/EditableField/styles/EditableField.Truncate.css.ts
  src/components/EditableField/styles/EditableField.css.ts
  src/constants/Keys.ts
  stories/EditableField.stories.js
Labels: feature 💅

#661 Copy GreeterCard and GreeterRow functionality into MessageCard and MessageRow components
  src/components/MessageCard/MessageCard.Button.tsx
  src/components/MessageCard/MessageCard.tsx
  src/components/MessageCard/MessageCard.utils.ts
  src/components/MessageCard/README.md
  src/components/MessageCard/__tests__/MessageCard.Button.test.tsx
  src/components/MessageCard/__tests__/MessageCard.test.tsx
  src/components/MessageCard/index.ts
  src/components/MessageCard/styles/MessageCard.css.ts
  src/components/MessageRow/MessageRow.tsx
  src/components/MessageRow/MessageRow.utils.ts
  src/components/MessageRow/README.md
  src/components/MessageRow/__tests__/MessageRow.test.tsx
  src/components/MessageRow/index.ts
  src/components/MessageRow/styles/MessageRow.css.ts
  src/components/index.ts
  stories/MessageCard.stories.js
  stories/MessageRow.stories.js
Labels: minor ✌️, refactor ♻️

#666 Add a new prop to Chat to change the position of the meta block
  src/components/Message/Message.Chat.tsx
  src/components/Message/Message.ChatBlock.tsx
  src/components/Message/__tests__/Message.Chat.test.js
  stories/Message/Message.Chat.stories.js
Labels: enhancement ✨

#671 Update Condtional Operation font weight
  src/components/Condition/Condition.Operator.tsx
Labels: enhancement ✨, patch ☝️
