Repository helpscout/hsds-react, pull requests merged in 2019-03, with the labels that each got.

#509 Memoize Fix
  jest.config.js
  package-lock.json
  package.json
  src/components/Button/ButtonV2.js
  src/utilities/__tests__/memoize.test.ts
  src/utilities/memoize.ts
  src/utilities/memoizeOne.js
Labels: bug 🐛, refactor ♻️, stability 💪

#507 Add handy open scripts
  package.json
Labels: enhancement ✨

#503 Add Nav component
  .storybook/addons.js
  package-lock.json
  package.json
  src/@types/helpscout__fancy/index.d.ts
  src/components/Message/__tests__/Action.test.js
  src/components/Nav/Nav.Item.tsx
  src/components/Nav/Nav.css.ts
  src/components/Nav/Nav.tsx
  src/components/Nav/Nav.utils.ts
  src/components/Nav/README.md
  src/components/Nav/__tests__/Nav.Item.test.tsx
  src/components/Nav/__tests__/Nav.test.tsx
  src/components/Nav/docs/Item.md
  src/components/Nav/docs/Nav.md
  src/components/Nav/index.ts
  src/components/NavLink/NavLink.tsx
  src/components/NavLink/README.md
  src/components/Text/Text.tsx
  src/components/Text/__tests__/Text.test.tsx
  src/components/Text/styles/Text.css.ts
  src/components/Toolbar/Block.js
  src/components/Toolbar/Item.js
  src/components/Toolbar/Toolbar.Block.tsx
  src/components/Toolbar/Toolbar.Item.tsx
  src/components/Toolbar/Toolbar.Shadow.tsx
  src/components/Toolbar/Toolbar.css.ts
  src/components/Toolbar/Toolbar.js
  src/components/Toolbar/Toolbar.tsx
  src/components/Toolbar/Toolbar.types.ts
  src/components/Toolbar/Toolbar.utils.ts
  src/components/Toolbar/__tests__/Block.test.js
  src/components/Toolbar/__tests__/Item.test.js
  src/components/Toolbar/__tests__/Shadow.test.js
  src/components/Toolbar/__tests__/Toolbar.test.js
  src/components/Toolbar/index.ts
  src/components/Toolbar/propTypes.js
  src/components/index.js
  src/styles/components/Toolbar/Toolbar.scss
  src/styles/components/Toolbar/ToolbarShadow.scss
  src/styles/components/Toolbar/ToolbarWrapper.scss
  src/styles/components/Toolbar/__index.scss
  stories/Nav.stories.js
  stories/NavLink.stories.js
Labels: feature 💅, refactor ♻️

#506 GreeterCard Component
  .storybook/storybook.css
  src/components/Button/Button.css.js
  src/components/GreeterCard/GreeterCard.Button.tsx
  src/components/GreeterCard/GreeterCard.css.ts
  src/components/GreeterCard/GreeterCard.tsx
  src/components/GreeterCard/GreeterCard.utils.ts
  src/components/GreeterCard/README.md
  src/components/GreeterCard/__tests__/GreeterCard.Button.test.tsx
  src/components/GreeterCard/__tests__/GreeterCard.test.tsx
  src/components/GreeterCard/index.ts
  src/components/Text/types.ts
  src/components/index.js
  src/styles/configs/colors.ts
  src/styles/configs/constants.ts
  src/styles/utilities/__tests__/font.test.ts
  src/styles/utilities/__tests__/makeBrandColors.test.ts
  src/styles/utilities/color.ts
  src/styles/utilities/font.ts
  stories/GreeterCard.stories.js
Labels: feature 💅, refactor ♻️

#510 Update chat components to use raw body property
  src/components/ChatTranscript/Item.js
  src/components/ChatTranscript/LineItem.js
  src/components/ChatTranscript/__tests__/Item.test.js
  src/components/ChatTranscript/__tests__/LineItem.test.js
  src/components/Message/Bubble.js
  src/components/Message/__tests__/Bubble.test.js
  src/utilities/__tests__/strings.test.js
  src/utilities/strings.ts
  stories/ChatTranscript/fixture/data.js
  stories/Message/Message.Chat.stories.js
  stories/Message/Message.default.stories.js
Labels: enhancement ✨

#513 Fancy: Fix Emotion build
  package-lock.json
  package.json
Labels: bug 🐛

#515 Dropdown: Fix ComboBox positioning with shouldDropDirectionUpdate
  .vscode/settings.json
  src/components/ComboBox/ComboBox.tsx
  src/components/ComboBox/__tests__/ComboBox.test.tsx
  src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
  src/components/Dropdown/V2/Dropdown.store.js
  src/components/Dropdown/V2/Dropdown.types.ts
  src/components/Dropdown/V2/__tests__/Dropdown.MenuContainer.test.tsx
  src/components/Dropdown/V2/docs/Dropdown.md
  stories/ComboBox.stories.js
Labels: bug 🐛, patch ☝️

#516 Chat transcript safe body support
  src/components/ChatTranscript/Item.js
  src/components/ChatTranscript/LineItem.js
  src/components/ChatTranscript/__tests__/Item.test.js
  src/components/ChatTranscript/__tests__/LineItem.test.js
  src/components/ChatTranscript/docs/Item.md
  src/utilities/strings.ts
  stories/ChatTranscript/ChatTranscript.stories.js
Labels: enhancement ✨, patch ☝️

#518 Dropdown: Position fixes (with Modal/Text Input)
  package-lock.json
  package.json
  src/components/ComboBox/ComboBox.tsx
  src/components/ComboBox/__tests__/ComboBox.test.tsx
  src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
  src/components/Dropdown/V2/Dropdown.store.js
  src/components/Dropdown/V2/Dropdown.types.ts
  src/components/Dropdown/V2/__tests__/Dropdown.MenuContainer.test.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.store.test.ts
  src/components/Dropdown/V2/docs/Dropdown.md
  stories/AutoDropdown.QA.stories.js
Labels: bug 🐛, patch ☝️

#517 Improve the utility to convert URLs (and emails) to links
  src/components/ChatTranscript/Item.js
  src/components/Message/Bubble.js
  src/utilities/__tests__/strings.test.js
  src/utilities/strings.ts
Labels: enhancement ✨, patch ☝️

#512 Add GreeterRow + Accordion.Link component
  package-lock.json
  src/components/Accordion/Accordion.Body.tsx
  src/components/Accordion/Accordion.Link.tsx
  src/components/Accordion/Accordion.Section.tsx
  src/components/Accordion/Accordion.Title.tsx
  src/components/Accordion/Accordion.css.ts
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/Accordion.types.ts
  src/components/Accordion/Accordion.utils.ts
  src/components/Accordion/Section.js
  src/components/Accordion/Title.js
  src/components/Accordion/__tests__/Accordion.Body.test.js
  src/components/Accordion/__tests__/Accordion.Link.test.js
  src/components/Accordion/__tests__/Accordion.Section.test.js
  src/components/Accordion/__tests__/Accordion.Title.test.js
  src/components/Accordion/__tests__/Accordion.test.js
  src/components/Accordion/__tests__/Accordion.utils.test.js
  src/components/Accordion/docs/Accordion.md
  src/components/Accordion/docs/Link.md
  src/components/Accordion/docs/Section.md
  src/components/Accordion/docs/Title.md
  src/components/Accordion/index.js
  src/components/Accordion/index.ts
  src/components/Accordion/styles/Accordion.css.js
  src/components/Accordion/types.js
  src/components/Accordion/utils.js
  src/components/Collapsible/Collapsible.tsx
  src/components/GreeterRow/GreeterRow.css.ts
  src/components/GreeterRow/GreeterRow.tsx
  src/components/GreeterRow/GreeterRow.utils.ts
  src/components/GreeterRow/README.md
  src/components/GreeterRow/__tests__/GreeterRow.test.tsx
  src/components/GreeterRow/index.ts
  src/components/Icon/icons.js
  src/components/Icon/styles/Icon.css.js
  src/components/PropProvider/propConnect.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/index.js
  src/icons/pause.svg
  src/utilities/__tests__/component.test.js
  src/utilities/component.ts
  src/utilities/is.ts
  stories/Accordion.stories.js
  stories/GreeterRow.stories.js
  stories/Tooltip.stories.js
Labels: feature 💅, minor ✌️, refactor ♻️

#519 Input: Add onEnterDown and onEnterUp
  src/components/Input/Input.js
  src/components/Input/__tests__/Input.test.js
  src/components/Input/docs/Input.md
  stories/Input.stories.js
Labels: enhancement ✨, patch ☝️

#525 PropProvider: Fix rendering for empty array
  src/components/PropProvider/PropProvider.tsx
  src/components/PropProvider/__tests__/PropProvider.test.js
  src/utilities/__tests__/component.test.js
  src/utilities/component.ts
Labels: bug 🐛, patch ☝️

#527 Add Aktiv Grotesk support in storybook
  .storybook/font-hs-app.css
  .storybook/storybook.css
  stories/Text.stories.tsx
  stories/utils/withAktiv.js
Labels: enhancement ✨, minor ✌️

#526 Button: Fix mapping of props.theme.brandColor
  src/components/Button/Button.css.js
  stories/GreeterCard.stories.js
Labels: bug 🐛, patch ☝️

#530 Fix renderAsSingleChild handling of Array
  package-lock.json
  package.json
  src/utilities/__tests__/component.test.js
  src/utilities/component.ts
Labels: bug 🐛, hot fix 🔥, patch ☝️

#539 Reduce import size (of SVG) with adapters
  .storybook/config.js
  README.md
  package-lock.json
  package.json
  src/adapters/__tests__/adapters.app.test.js
  src/adapters/__tests__/adapters.embed.test.js
  src/adapters/app.js
  src/adapters/embed.js
  src/components/Icon/Icon.js
  src/components/Icon/README.md
  src/components/Icon/__tests__/Icon.load.test.js
  src/components/Icon/__tests__/Icon.utils.test.js
  src/components/Icon/__tests__/icons.test.js
  src/components/Icon/icons.all.js
  src/components/Icon/icons.embed.js
  src/components/Icon/icons.js
  src/components/Icon/index.js
  src/components/Icon/utils.js
  src/components/Illo/Illo.js
  src/components/Illo/README.md
  src/components/Illo/__tests__/Illo.load.test.js
  src/components/Illo/__tests__/illos.test.js
  src/components/Illo/illos.all.js
  src/components/Illo/illos.embed.js
  src/components/Illo/illos.js
  src/components/Illo/index.js
  stories/Illo.stories.js
Labels: enhancement ✨, high priority ⚠️, minor ✌️

#536 Popover/Tooltip: Improve left/right placement
  src/components/Pop/Popper.js
  src/components/Pop/__tests__/Popper.test.js
  stories/Popover.stories.js
Labels: bug 🐛, patch ☝️

#544 Icon: Remove scaling
  src/components/Icon/styles/Icon.css.js
Labels: hot fix 🔥

#547 Icon: Remove/replace 20x20 icons with proper 24x24 svgs
  package-lock.json
  package.json
  src/components/Icon/icons.all.js
  src/components/Icon/icons.embed.js
  src/components/Sortable/DragHandle.js
  src/icons/attachment.svg
  src/icons/block-arrow-down.svg
  src/icons/block-arrow-up.svg
  src/icons/chat-active.svg
  src/icons/check.svg
  src/icons/checkmark.svg
  src/icons/chevron-down.svg
  src/icons/chevron-left.svg
  src/icons/chevron-right.svg
  src/icons/chevron-up.svg
  src/icons/clock-large.svg
  src/icons/collapse.svg
  src/icons/drag.svg
  src/icons/emoji-activity.svg
  src/icons/emoji-animals-nature.svg
  src/icons/emoji-flags.svg
  src/icons/emoji-food-drink.svg
  src/icons/emoji-objects.svg
  src/icons/emoji-symbols.svg
  src/icons/emoji-travel-places.svg
  src/icons/helpscout-logo.svg
  src/icons/image-add.svg
  src/icons/meatball.svg
  src/icons/small-paperclip.svg
  src/icons/spinner.svg
  src/icons/tick-small.svg
  stories/Icon.stories.js
Labels: bug 🐛, high priority ⚠️, patch ☝️

#537 Input: Fixed Action + Error rendering
  src/components/Input/Input.js
  src/components/Input/styles/BackdropV2.css.js
  src/components/Input/styles/Input.css.js
  src/styles/utilities/__tests__/font.test.ts
  src/styles/utilities/font.ts
  stories/Input.stories.js
Labels: bug 🐛, patch ☝️

#533 Add HSDS version to window
  package.json
  scripts/make-version.js
  src/components/PropProvider/propConnect.tsx
  src/utilities/__tests__/info.test.ts
  src/utilities/info.ts
  src/utilities/pkg.ts
Labels: enhancement ✨, patch ☝️

#534 Link: Refactor + add voidOnClick
  src/components/Link/Link.css.ts
  src/components/Link/Link.tsx
  src/components/Link/README.md
  src/components/Link/__tests__/Link.test.js
  src/components/Link/index.ts
  src/styles/components/Link.scss
  stories/Link.stories.js
Labels: enhancement ✨, minor ✌️, refactor ♻️

#531 HS-App wrapper & decorator
  .storybook/storybook.css
  src/components/HsApp/HsApp.css.js
  src/components/HsApp/HsApp.tsx
  src/components/HsApp/HsApp.utils.ts
  src/components/HsApp/Nav.tsx
  src/components/HsApp/README.md
  src/components/HsApp/Sidenav.tsx
  src/components/HsApp/__tests__/HsApp.test.js
  src/components/HsApp/index.ts
  src/components/index.js
  stories/Accordion.stories.js
  stories/utils/index.js
  stories/utils/withHsApp.js
Labels: enhancement ✨, minor ✌️

#540 Updates Scrollable component to support horizontal scrolling
  package-lock.json
  src/components/Scrollable/README.md
  src/components/Scrollable/Scrollable.css.ts
  src/components/Scrollable/Scrollable.tsx
  src/components/Scrollable/__tests__/Scrollable.test.js
  src/components/Scrollable/index.ts
  stories/Scrollable.stories.js
Labels: enhancement ✨, minor ✌️

#549 Dropdown: Fix top/left position calculation with window.scroll values
  src/components/Dropdown/V2/Dropdown.MenuContainer.tsx
  src/components/Dropdown/V2/Dropdown.MenuContainer.utils.ts
  src/components/Dropdown/V2/__tests__/Dropdown.MenuContainer.utils.test.ts
Labels: bug 🐛, hot fix 🔥, patch ☝️
