Repository helpscout/hsds-react, pull requests merged in 2019-11, with the labels that each got.

#736 Add percy integration
  .gitignore
  package-lock.json
  package.json
Labels: feature 💅

#738 Make Dropdown.Item polymorphic
  package.json
  src/components/Dropdown/V2/Dropdown.Item.tsx
  src/components/Dropdown/V2/Dropdown.css.js
  src/components/Dropdown/V2/__tests__/Dropdown.Item.test.tsx
  stories/DropdownV2.stories.js
Labels: enhancement ✨

#740 Allow item props to be updated on validate/save
  src/components/EditableField/EditableField.tsx
  src/components/EditableField/EditableField.types.ts
  src/components/EditableField/__tests__/EditableField.test.tsx
Labels: enhancement ✨

#744 Remove Storybook Console addon
  .storybook/config.js
  package-lock.json
  package.json
Labels: bug 🐛

#743 Add Emoji svg to Embed icon bundle
  src/components/Icon/icons.embed.js
Labels: enhancement ✨

#741 Fix bug in ChatList story
  stories/ChatList/ChatList.stories.js
Labels: bug 🐛

#742 Prevent pointer events from DropdownTrigger children
  src/components/Dropdown/V2/Dropdown.css.js
Labels: bug 🐛

#746 Update Table.Row to use dynamic classNames
  src/components/Table/README.md
  src/components/Table/Table.Row.tsx
  src/components/Table/__tests__/Table.test.js
  src/components/Table/docs/Columns.md
  stories/Table/Table.stories.js
Labels: enhancement ✨

#749 HSDS-81: DotStepper Component
  .storybook/config.js
  jest.config.js
  src/components/DotStepper/DotStepper.css.js
  src/components/DotStepper/DotStepper.js
  src/components/DotStepper/DotStepper.stories.js
  src/components/DotStepper/DotStepper.test.js
  src/components/DotStepper/README.md
  src/components/DotStepper/index.js
  src/components/index.ts
Labels: feature 💅, minor ✌️

#753 HSAPP-734 Create a Form component
  src/components/Form/Actions/Form.Actions.css.js
  src/components/Form/Actions/Form.Actions.js
  src/components/Form/Actions/Form.Actions.test.js
  src/components/Form/Actions/README.md
  src/components/Form/Form.js
  src/components/Form/Form.stories.js
  src/components/Form/Form.test.js
  src/components/Form/README.md
  src/components/Form/index.js
  src/components/index.ts
Labels: feature 💅

#758 Changes Table name of prop theme to skin to avoid clashes with s…
  package-lock.json
  src/components/Table/README.md
  src/components/Table/Table.tsx
  src/components/Table/Table.types.ts
  src/components/Table/__tests__/Table.test.js
  src/components/Table/docs/Skins.md
  src/components/Table/styles/skins.js
  stories/Table/Table.stories.js
  stories/Table/TableCustomizer.js
  stories/Table/TablePlayground.js
Labels: bug 🐛

#760 Table collapse and custom expander text
  src/components/Table/README.md
  src/components/Table/Table.Body.tsx
  src/components/Table/Table.tsx
  src/components/Table/Table.types.ts
  src/components/Table/__tests__/Table.test.js
  stories/Table/Table.stories.js
Labels: enhancement ✨
