Repository helpscout/hsds-react, pull requests merged in 2019-06, with the labels that each got.

#642 Adds TypeScript linting
  .eslintrc
  .eslintrc.js
  .vscode/settings.json
  package-lock.json
  package.json
Labels: patch ☝️, stability 💪, tooling :wrench:

#629 Styled: Adding "Extras"
  package-lock.json
  package.json
  src/@types/helpscout__fancy/index.d.ts
  src/components/styled/README.md
  src/components/styled/__tests__/styled.extras.test.tsx
  src/components/styled/index.ts
  src/components/styled/styled.ts
  src/styles/utilities/color.ts
  src/utilities/__tests__/color/rgb.test.ts
  src/utilities/color.ts
Labels: feature 💅, minor ✌️

#644 Add new social icons
  .travis.yml
  package-lock.json
  src/components/Icon/icons.all.js
  src/icons/social-aboutme.svg
  src/icons/social-aol.svg
  src/icons/social-facebook.svg
  src/icons/social-flicker.svg
  src/icons/social-foursquare.svg
  src/icons/social-gplus.svg
  src/icons/social-hangouts.svg
  src/icons/social-icq.svg
  src/icons/social-linkedin.svg
  src/icons/social-msn.svg
  src/icons/social-qq.svg
  src/icons/social-quora.svg
  src/icons/social-skype.svg
  src/icons/social-twitter.svg
  src/icons/social-xmpp.svg
  src/icons/social-yahoo.svg
  src/icons/social-youtube.svg
Labels: enhancement ✨, minor ✌️

#645 Styled: Rollback extra styles
  package-lock.json
  package.json
  src/@types/helpscout__fancy/index.d.ts
  src/components/styled/README.md
  src/components/styled/__tests__/styled.extras.test.tsx
  src/components/styled/index.ts
  src/components/styled/styled.ts
  src/styles/utilities/color.ts
  src/utilities/__tests__/color/rgb.test.ts
  src/utilities/color.ts
  src/utilities/pkg.ts
Labels: hot fix 🔥, patch ☝️

#637 Add EmojiPicker component
  src/components/Dropdown/V2/Dropdown.Menu.tsx
  src/components/Dropdown/V2/Dropdown.Renderer.tsx
  src/components/Dropdown/V2/Dropdown.store.js
  src/components/Dropdown/V2/Dropdown.types.ts
  src/components/EmojiPicker/EmojiPicker.Emoji.tsx
  src/components/EmojiPicker/EmojiPicker.Item.tsx
  src/components/EmojiPicker/EmojiPicker.tsx
  src/components/EmojiPicker/EmojiPicker.types.ts
  src/components/EmojiPicker/EmojiPicker.utils.ts
  src/components/EmojiPicker/README.md
  src/components/EmojiPicker/__tests__/EmojiPicker.Item.test.tsx
  src/components/EmojiPicker/__tests__/EmojiPicker.test.tsx
  src/components/EmojiPicker/emojiSet.ts
  src/components/EmojiPicker/index.ts
  src/components/EmojiPicker/styles/EmojiPicker.css.ts
  stories/EmojiPicker.stories.js
Labels: feature 💅

#647 Add time of day icons. Update fill color
  src/components/Icon/icons.all.js
  src/components/Icon/styles/Icon.css.js
  src/icons/caret-down.svg
  src/icons/caret-left.svg
  src/icons/caret-right.svg
  src/icons/caret-up.svg
  src/icons/spinner.svg
  src/icons/time-day-moon.svg
  src/icons/time-day-sun.svg
Labels: enhancement ✨, minor ✌️

#649 Fixing issue with icons color
  src/components/Icon/styles/Icon.css.js
  src/icons/time-day-sun.svg
Labels: hot fix 🔥

#650 Update default animationSequence and add trunctate
  src/components/GreeterCard/GreeterCard.tsx
Labels: enhancement ✨, patch ☝️

#648 Emoji Picker refinements
  src/components/EmojiPicker/EmojiPicker.tsx
  src/components/EmojiPicker/__tests__/EmojiPicker.test.tsx
  src/components/EmojiPicker/emojiSet.ts
  src/components/EmojiPicker/styles/EmojiPicker.css.ts
  stories/EmojiPicker.stories.js
Labels: enhancement ✨, patch ☝️

#651 ConditionField: Pass props through to Flexy
  src/components/ConditionField/ConditionField.tsx
Labels: enhancement ✨, patch ☝️
