Repository helpscout/hsds-react, pull requests merged in 2019-10, with the labels that each got.

#717 HSDS-77 Fix Truncate component to show tooltip when truncated on splitter'
  src/components/Truncate/README.md
  src/components/Truncate/Truncate.tsx
  src/components/Truncate/Truncate.utils.ts
  src/components/Truncate/__tests__/Truncate.test.js
  src/components/Truncate/styles/Truncate.WithSplitter.css.ts
  stories/Truncate.stories.js
Labels: bug 🐛, patch ☝️

#715 EditableTextarea component
  package-lock.json
  package.json
  src/components/EditableField/EditableField.types.ts
  src/components/EditableTextarea/EditableTextarea.tsx
  src/components/EditableTextarea/EditableTextarea.types.ts
  src/components/EditableTextarea/EditableTextarea.utils.ts
  src/components/EditableTextarea/README.md
  src/components/EditableTextarea/__tests__/EditableTextarea.test.tsx
  src/components/EditableTextarea/index.ts
  src/components/EditableTextarea/styles/EditableTextarea.css.ts
  src/utilities/debounce.ts
  stories/EditableField.stories.js
  stories/EditableTextarea.stories.js
Labels: feature 💅

#723 Adds validation mechanism to EditableTextarea
  src/components/EditableField/__tests__/EditableField.Input.test.tsx
  src/components/EditableTextarea/EditableTextarea.tsx
  src/components/EditableTextarea/EditableTextarea.types.ts
  src/components/EditableTextarea/EditableTextarea.utils.ts
  src/components/EditableTextarea/README.md
  src/components/EditableTextarea/__tests__/EditableTextarea.test.tsx
  src/components/EditableTextarea/styles/EditableTextarea.css.ts
  src/components/Modal/Modal.Body.tsx
  src/components/Modal/Modal.types.ts
  src/components/Modal/docs/Body.md
  stories/EditableField.stories.js
  stories/EditableTextarea.stories.js
Labels: enhancement ✨

#721 Add content, heading and maxWidth to the RadioCard component
  src/components/RadioCard/README.md
  src/components/RadioCard/RadioCard.tsx
  src/components/RadioCard/RadioCard.types.ts
  src/components/RadioCard/__tests__/RadioCard.test.js
  src/components/RadioCard/styles/RadioCard.css.ts
  stories/RadioCard.stories.js
Labels: enhancement ✨

#725 Adds floating labels to editable field and textarea
  package-lock.json
  package.json
  src/components/EditableField/EditableField.tsx
  src/components/EditableField/EditableField.types.ts
  src/components/EditableField/EditableField.utils.ts
  src/components/EditableField/__tests__/EditableField.test.tsx
  src/components/EditableField/styles/EditableField.Input.css.ts
  src/components/EditableTextarea/EditableTextarea.tsx
  src/components/EditableTextarea/EditableTextarea.types.ts
  src/components/EditableTextarea/__tests__/EditableTextarea.test.tsx
  src/components/EditableTextarea/styles/EditableTextarea.css.ts
  src/utilities/pkg.ts
  stories/EditableField.stories.js
  stories/EditableTextarea.stories.js
Labels: enhancement ✨

#729 Fixes accessibility issues on empty Editable Textareas
  package.json
  src/components/EditableTextarea/EditableTextarea.tsx
  src/components/EditableTextarea/styles/EditableTextarea.css.ts
  src/utilities/pkg.ts
Labels: bug 🐛

#727 HSDS-77 Fixes for Truncate
  src/components/Truncate/README.md
  src/components/Truncate/Truncate.tsx
  src/components/Truncate/Truncate.utils.ts
  src/components/Truncate/__tests__/Truncate.test.js
  src/components/Truncate/styles/Truncate.WithSplitter.css.ts
  stories/Truncate.stories.js
Labels: bug 🐛, patch ☝️

#732 PROD-390 Add scheme to urls if missing
  src/components/EditableField/EditableField.Actions.tsx
  src/components/EditableField/__tests__/EditableField.Actions.test.tsx
  src/utilities/__tests__/strings.test.js
  src/utilities/__tests__/urls.test.js
  src/utilities/index.ts
  src/utilities/strings.ts
  src/utilities/urls.ts
  stories/EditableField.stories.js
Labels: bug 🐛, patch ☝️

#734 Add missing component API props
  src/components/EditableTextarea/EditableTextarea.tsx
  src/components/EditableTextarea/EditableTextarea.types.ts
  src/components/EditableTextarea/__tests__/EditableTextarea.test.tsx
Labels: bug 🐛
