Repository helpscout/hsds-react, pull requests merged in 2019-09, with the labels that each got.

#694 Fix z-index issue in Avatar/Status UI
  src/components/Avatar/styles/Avatar.css.ts
Labels: bug 🐛

#689 Dropdown V2 adjustments
  src/components/Dropdown/V2/Dropdown.Container.tsx
  src/components/Dropdown/V2/Dropdown.Item.tsx
  src/components/Dropdown/V2/Dropdown.actionTypes.ts
  src/components/Dropdown/V2/Dropdown.actions.ts
  src/components/Dropdown/V2/Dropdown.reducer.ts
  src/components/Dropdown/V2/__tests__/Dropdown.Item.test.tsx
  src/components/Dropdown/V2/__tests__/Dropdown.actions.test.ts
  src/components/Dropdown/V2/__tests__/Dropdown.reducer.test.ts
Labels: enhancement ✨

#696 Allow Dropdown Items to have a type of `header`
  src/components/Dropdown/V2/Dropdown.Item.tsx
Labels: enhancement ✨

#702 Fix Avatar that was flashing when loading was completed
  src/components/Avatar/Avatar.Crop.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/__tests__/Avatar.test.js
  stories/Avatar/Avatar.stories.js
Labels: minor ✌️

#701 Add keypress event callbacks to EditableField
  package-lock.json
  src/components/EditableField/EditableField.Input.tsx
  src/components/EditableField/EditableField.tsx
  src/components/EditableField/EditableField.types.ts
  src/components/EditableField/EditableFieldComposite.tsx
  src/components/EditableField/__tests__/EditableField.Input.test.tsx
  src/components/EditableField/__tests__/EditableField.test.tsx
  src/components/EditableField/constants.tsx
  stories/EditableField.stories.js
Labels: enhancement ✨, minor ✌️

#706 Upgrade colorway to add missing indigo and whaletail color
  package-lock.json
  package.json
  src/styles/configs/_colorway.scss
  src/styles/configs/colorway.ts
Labels: enhancement ✨, minor ✌️

#700 Upgrade typescript-eslint & eslint
  package-lock.json
  package.json
Labels: minor ✌️

#687 Fix input disabled state in storybook to reflect HSDS
  stories/Input.stories.js
Labels: enhancement ✨

#703 Add "splitter" prop to <Truncate />
  src/components/Truncate/Truncate.tsx
  src/components/Truncate/Truncate.types.ts
  src/components/Truncate/Truncate.utils.ts
  src/components/Truncate/__tests__/Truncate.test.js
  src/components/Truncate/styles/Truncate.WithSplitter.css.ts
  stories/Truncate.stories.js
Labels: enhancement ✨

#709 Allow for richer validation
  src/components/EditableField/EditableField.tsx
  src/components/EditableField/EditableField.types.ts
  src/components/PortalWrapper/PortalWrapper.tsx
  src/components/PortalWrapper/__tests__/PortalWrapper.test.js
  src/utilities/pkg.ts
  stories/EditableField.stories.js
  stories/Modal.stories.js
Labels: enhancement ✨, minor ✌️

#711 Upgrades to Storybook 5.2
  .storybook/webpack.config.js
  package-lock.json
  package.json
  src/styles/configs/_colorway.scss
  src/styles/configs/colorway.ts
Labels: enhancement ✨
