Repository helpscout/hsds-react, pull requests merged in 2020-04, with the labels that each got.

#807 Focus improvements
  src/components/CopyInput/CopyInput.jsx
  src/components/CopyInput/CopyInput.stories.js
  src/components/Modal/Modal.jsx
  src/components/VerificationCode/VerificationCode.jsx
  src/components/VerificationCode/VerificationCode.stories.js
  src/components/VerificationCode/VerificationCode.test.js
  src/components/VerificationCode/VerificationCode.utils.js
Labels: enhancement ✨, minor ✌️, v3

#808 Merge changes from Focus improvements (#807)
  src/components/CopyInput/CopyInput.tsx
  src/components/Modal/Modal.tsx
  src/components/VerificationCode/VerificationCode.js
  src/components/VerificationCode/VerificationCode.stories.js
  src/components/VerificationCode/VerificationCode.test.js
  src/components/VerificationCode/VerificationCode.utils.js
  stories/CopyInput.stories.js
Labels: enhancement ✨, hot fix 🔥

#809 Add disabled props + Fix modal focus trapping
  src/components/Modal/Modal.ActionFooter.jsx
  src/components/Modal/Modal.stories.js
  src/utilities/__tests__/focus/findCurrentFocusedNodeIndex.test.js
  src/utilities/__tests__/focus/findFirstFocusableNode.test.js
  src/utilities/__tests__/focus/findFocusableNodes.test.js
  src/utilities/__tests__/focus/findLastFocusableNode.test.js
  src/utilities/__tests__/focus/findNextFocusableNode.test.js
  src/utilities/__tests__/focus/findPreviousFocusableNode.test.js
  src/utilities/__tests__/focus/focusNextFocusableNode.test.js
  src/utilities/__tests__/focus/focusPreviousFocusableNode.test.js
  src/utilities/focus.js
Labels: bug 🐛, patch ☝️

#810 Merge changes from Add disabled props + Fix modal focus trapping (#809)
  jest.config.js
  src/components/Modal/Modal.ActionFooter.tsx
  src/components/Modal/Modal.types.ts
  src/utilities/__tests__/focus/findCurrentFocusedNodeIndex.test.js
  src/utilities/__tests__/focus/findFirstFocusableNode.test.js
  src/utilities/__tests__/focus/findFocusableNodes.test.js
  src/utilities/__tests__/focus/findLastFocusableNode.test.js
  src/utilities/__tests__/focus/findNextFocusableNode.test.js
  src/utilities/__tests__/focus/findPreviousFocusableNode.test.js
  src/utilities/__tests__/focus/focusNextFocusableNode.test.js
  src/utilities/__tests__/focus/focusPreviousFocusableNode.test.js
  src/utilities/focus.ts
  stories/Modal.stories.js
Labels: bug 🐛, hot fix 🔥, patch ☝️

#811 Tab focus cycling in Modal
  src/components/Modal/Modal.HeaderV2.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.stories.js
  src/components/Pop/Arrow.jsx
  src/components/VerificationCode/VerificationCode.jsx
  src/components/VerificationCode/VerificationCode.stories.js
  src/components/VerificationCode/VerificationCode.test.js
Labels: hot fix 🔥, patch ☝️

#812 Merge changes from Tab focus cycling in Modal (#811)
  src/components/Modal/Modal.HeaderV2.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/Modal.types.ts
  src/components/VerificationCode/VerificationCode.js
  src/components/VerificationCode/VerificationCode.stories.js
  src/components/VerificationCode/VerificationCode.test.js
Labels: hot fix 🔥, patch ☝️

#813 Fix codemod
  package-lock.json
  package.json
  scripts/codemod/cli.js
Labels: hot fix 🔥

#814 Configurable codemod import package name
  package.json
  scripts/codemod/cli.js
  scripts/codemod/transforms/ReplaceImportsTransform.js
Labels: enhancement ✨, patch ☝️

#817 CopyButton minor tweak: updates the checkmark size to match the button size
  src/components/CopyButton/CopyButton.tsx
  src/components/CopyInput/CopyInput.tsx
  stories/CopyButton.stories.js
Labels: patch ☝️

#819 Add Alert UI updates from v3
  src/components/Alert/Alert.tsx
  src/components/Alert/styles/Alert.css.ts
Labels: enhancement ✨, patch ☝️
