Repository helpscout/hsds-react, pull requests merged in 2020-06, with the labels that each got.

#834 Add MessageCard ability to render html
  src/components/MessageCard/MessageCard.css.js
  src/components/MessageCard/MessageCard.jsx
  src/components/MessageCard/MessageCard.stories.js
  src/components/MessageCard/MessageCard.test.js
Labels: enhancement ✨, minor ✌️

#836 Force FilteredList & Truncate to append tooltip on the body
  package-lock.json
  package.json
  src/components/FilteredList/FilteredList.jsx
  src/components/FilteredList/FilteredList.stories.js
  src/components/Tooltip/Tooltip.css.js
  src/components/Truncate/Truncate.jsx
  src/utilities/pkg.js
Labels: bug 🐛, minor ✌️

#838 Fix cypress
  .eslintrc.js
  cypress/integration/Button.js
  cypress/integration/Dropdown.js
  cypress/integration/Modal.js
  cypress/integration/Pagination.js
  cypress/integration/Tooltip.js
  cypress/support/commands.js
  cypress/tsconfig.json
  package-lock.json
  package.json
  src/components/Button/Button.stories.js
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.stories.js
  src/components/Portal/Portal.jsx
Labels: bug 🐛

#832 Fix typing indicator styling issue
  src/components/Message/Message.Bubble.css.js
Labels: bug 🐛

#845 Fix: Tooltips on Input Errors Do Not Display Correctly
  src/components/Input/Input.jsx
Labels: bug 🐛, v3

#842 Update secondary & tertiary buttons
  src/components/Button/Button.config.js
Labels: enhancement ✨, patch ☝️

#844 Change CopyInput to use copy-small icon
  src/components/Button/Button.jsx
  src/components/CopyButton/CopyButton.css.js
  src/components/CopyButton/CopyButton.jsx
  src/components/CopyButton/CopyButton.stories.js
  src/components/CopyInput/CopyInput.jsx
  src/icons/copy-small.svg
Labels: patch ☝️

#847 Update modal v2 alert styles to match design specs
  src/components/Modal/Modal.Body.jsx
  src/components/Modal/Modal.HeaderV2.css.js
  src/components/Modal/Modal.css.js
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.stories.js
  src/components/Modal/__tests__/Modal.Body.test.js
Labels: enhancement ✨

#849 Refactor Accordion to use either an internal or external state
  package-lock.json
  package.json
  src/components/Accordion/Accordion.Section.jsx
  src/components/Accordion/Accordion.Title.jsx
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/Accordion.stories.mdx
  src/components/Accordion/Accordion.storiesHelpers.js
  src/components/Accordion/__tests__/Accordion.Body.test.js
  src/components/Accordion/__tests__/Accordion.Section.test.js
  src/components/Accordion/__tests__/Accordion.Title.test.js
  src/components/Accordion/__tests__/Accordion.test.js
  src/components/Accordion/docs/Accordion.md
  src/utilities/pkg.js
Labels: bug 🐛, enhancement ✨, patch ☝️

#852 Fixed differences between v2 and v3 in Accordion component
  src/components/Accordion/Accordion.Title.jsx
  src/components/Accordion/Accordion.css.js
  src/components/Sortable/Sortable.DragHandle.jsx
Labels: bug 🐛

#853 Only pass valid props within ActionSelect ContentResizer
  src/components/ActionSelect/ActionSelect.ContentResizer.jsx
Labels: bug 🐛, patch ☝️
