Repository helpscout/hsds-react, pull requests merged in 2020-12, with the labels that each got.

#893 Upgrade green & purple color
  package-lock.json
  package.json
  src/styles/configs/colorway.js
Labels: enhancement ✨

#894 Added onBodyClick prop to MessageCard component
  src/components/MessageCard/MessageCard.jsx
  src/components/MessageCard/MessageCard.test.js
Labels: enhancement ✨, patch ☝️

#896 Removed MessageList component
  src/components/MessageList/MessageList.css.js
  src/components/MessageList/MessageList.hsappstories.js
  src/components/MessageList/MessageList.jsx
  src/components/MessageList/MessageList.mockItems.js
  src/components/MessageList/MessageList.test.js
  src/components/MessageList/MessageRow.css.js
  src/components/MessageList/MessageRow.jsx
  src/components/MessageList/__mocks__/react-sortable-hoc.js
  src/components/MessageList/index.js
  src/components/index.js
Labels: refactor ♻️

#897 Use effect only shadow for MessageCard component
  src/components/MessageCard/MessageCard.css.js
  src/styles/mixins/depth.css.js
Labels: bug 🐛, patch ☝️
