Repository helpscout/hsds-react, pull requests merged in 2020-02, with the labels that each got.

#776 Increase Tooltip default zIndex for use in Modals
  src/components/Tooltip/Tooltip.tsx
  stories/Modal.stories.js
Labels: bug 🐛

#780 Create TypingDots Component
  package.json
  src/components/TypingDots/README.md
  src/components/TypingDots/TypingDots.tsx
  src/components/TypingDots/TypingDots.types.ts
  src/components/TypingDots/TypingDots.utils.ts
  src/components/TypingDots/__tests__/TypingDots.test.tsx
  src/components/TypingDots/index.ts
  src/components/TypingDots/styles/TypingDots.css.ts
  stories/TypingDots.stories.js
Labels: feature 💅

#782 Replace LoadingDots with TypingDots
  src/components/Message/Message.Bubble.tsx
  src/components/Message/__tests__/Message.Bubble.test.js
  src/components/index.ts
Labels: feature 💅

#783 Update ChatListItem and docs of TypingDots change
  src/components/ChatList/ChatList.Item.tsx
  src/components/ChatList/__tests__/Item.test.js
  src/components/ChatList/docs/Item.md
  src/components/Message/docs/Bubble.md
  src/components/Message/docs/Chat.md
  src/components/Message/docs/Question.md
  src/components/README.md
Labels: feature 💅

#788 Refactor Message.Action UI for HS App
  src/components/Message/Message.Action.tsx
  src/components/Message/Message.Attachment.tsx
  src/components/Message/Message.Bubble.tsx
  src/components/Message/Message.Chat.tsx
  src/components/Message/Message.ChatBlock.tsx
  src/components/Message/Message.Content.tsx
  src/components/Message/Message.Media.tsx
  src/components/Message/Message.tsx
  src/components/Message/Message.types.ts
  src/components/Message/__tests__/Message.Action.test.js
  src/components/Message/__tests__/Message.ChatBlock.test.js
  src/components/Message/docs/ChatBlock.md
  src/components/Message/styles/Action.css.js
  src/components/Message/styles/ChatBlock.css.js
Labels: feature 💅

#789 Fix Sortable Accordion Drag Handle Position
  src/components/Accordion/Accordion.css.js
Labels: bug 🐛, v3

#793 Remove wrapping span around the button childrens only when it's not loading
  src/components/Button/Button.css.js
  src/components/Button/Button.jsx
Labels: enhancement ✨, v3

#790 Modal V2
  src/components/Modal/Modal.ActionFooter.tsx
  src/components/Modal/Modal.Body.tsx
  src/components/Modal/Modal.HeaderV2.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/Modal.types.ts
  src/components/Modal/Modal.utils.ts
  src/components/Modal/__tests__/Modal.ActionFooter.test.js
  src/components/Modal/__tests__/Modal.Body.test.js
  src/components/Modal/__tests__/Modal.test.js
  src/components/Modal/docs/Modal.md
  src/components/Modal/styles/Modal.ActionFooter.css.js
  src/components/Modal/styles/Modal.Body.css.js
  src/components/Modal/styles/Modal.HeaderV2.css.js
  src/components/Modal/styles/Modal.css.js
  src/components/Overlay/styles/Overlay.css.js
  src/styles/configs/_colorway.scss
  src/styles/configs/colorway.ts
  src/utilities/easing.ts
  stories/Animate.stories.js
  stories/Modal.stories.js
Labels: enhancement ✨
