Repository helpscout/hsds-react, pull requests merged in 2020-07, with the labels that each got.

#857 Bug Fix: Radio stacked prop was not passing through to Choice element, so stacked styles never applied
  src/components/Radio/Radio.jsx
  src/components/Radio/Radio.stories.js
  src/components/Radio/Radio.test.js
Labels: bug 🐛, patch ☝️

#858 HSAPP-2429 Editable field with multi-values bug
  src/components/EditableField/EditableField.jsx
Labels: bug 🐛

#859 HSDS-158 Tooltip Fix: Text breaks mid-word
  src/components/Tooltip/Tooltip.css.js
Labels: bug 🐛, v3

#841 Fix MessageCard render issue
  src/components/MessageCard/MessageCard.css.js
  src/components/MessageCard/MessageCard.jsx
  src/components/MessageCard/MessageCard.stories.js
  src/components/MessageCard/MessageCard.test.js
Labels: bug 🐛, patch ☝️

#862 Add disabled support to SelectDropdown component
  src/components/Select/Select.css.js
  src/components/SelectDropdown/SelectDropdown.css.js
  src/components/SelectDropdown/SelectDropdown.jsx
  src/components/SelectDropdown/SelectDropdown.stories.js
Labels: bug 🐛

#864 Fix UI related bugs
  src/components/Condition/Condition.AddButton.jsx
  src/components/IconButton/IconButton.css.js
  src/components/IconButton/IconButton.stories.js
  src/components/MessageList/MessageList.stories.js
  src/components/MessageList/MessageRow.jsx
Labels: bug 🐛

#865 Change appendTo location for Tooltip inside Nav.Item
  src/components/Nav/Nav.Item.jsx
Labels: bug 🐛

#867 Fix CopyCode button sizing issue
  src/components/CopyButton/CopyButton.jsx
  src/components/CopyCode/CopyCode.jsx
  src/components/CopyCode/README.md
Labels: bug 🐛

#868 Bug Fixes: Popover placement prop is getting ignored, Verification Tooltip error rendering incorrectly
  src/components/Popover/Popover.jsx
  src/components/VerificationCode/VerificationCode.jsx
Labels: bug 🐛

#871 Bug fixes for CopyButton in Safari & Input Tooltip
  src/components/CopyButton/CopyButton.css.js
  src/components/Input/Input.jsx
Labels: bug 🐛

#866 Portal / React 16 API
  src/components/Dropdown/__tests__/Dropdown.MenuPortal.test.js
  src/components/Frame/Frame.jsx
  src/components/Frame/Frame.stories.mdx
  src/components/Frame/Frame.test.js
  src/components/Modal/Modal.stories.mdx
  src/components/Modal/__tests__/Modal.test.js
  src/components/Portal/Portal.Container.jsx
  src/components/Portal/Portal.jsx
  src/components/Portal/Portal.test.js
  src/components/PortalWrapper/PortalWrapper.Content.jsx
  src/components/PortalWrapper/PortalWrapper.jsx
  src/components/PortalWrapper/PortalWrapper.test.js
Labels: bug 🐛, enhancement ✨

#873 CopyInput can render as a Text Copy Button instead of Copy Icon
  src/components/CopyInput/CopyInput.jsx
  src/components/CopyInput/CopyInput.stories.mdx
  src/components/CopyInput/CopyInput.test.js
Labels: bug 🐛
