Repository helpscout/hsds-react, pull requests merged in 2020-05, with the labels that each got.

#821 COMMS-613 Add re-rendering on prop changes to ComboBox
  src/components/ComboBox/ComboBox.tsx
Labels: bug 🐛, patch ☝️

#820 COMMS-613 Dropdown Improvements
  src/components/Dropdown/V2/Dropdown.Trigger.tsx
  src/components/Dropdown/V2/Dropdown.css.js
Labels: bug 🐛, enhancement ✨, patch ☝️

#818 Refactor tooltip & popover to use Tippy
  VIDEOS.md
  __mocks__/popper.js.js
  package-lock.json
  package.json
  src/components/DotStepper/DotStepper.jsx
  src/components/Drop/README.md
  src/components/FilteredList/FilteredList.jsx
  src/components/Frame/Frame.stories.js
  src/components/Message/Message.Media.css.js
  src/components/Modal/Modal.HeaderV2.css.js
  src/components/Modal/Modal.HeaderV2.jsx
  src/components/Pop/Arrow.css.js
  src/components/Pop/Arrow.jsx
  src/components/Pop/Manager.js
  src/components/Pop/Pop.Portal.jsx
  src/components/Pop/Pop.css.js
  src/components/Pop/Pop.jsx
  src/components/Pop/Pop.utils.js
  src/components/Pop/Popper.jsx
  src/components/Pop/README.md
  src/components/Pop/Reference.jsx
  src/components/Pop/__tests__/Arrow.test.js
  src/components/Pop/__tests__/Manager.test.js
  src/components/Pop/__tests__/Pop.Portal.test.js
  src/components/Pop/__tests__/Pop.test.js
  src/components/Pop/__tests__/Popper.test.js
  src/components/Pop/__tests__/Reference.test.js
  src/components/Pop/docs/Arrow.md
  src/components/Pop/docs/Manager.md
  src/components/Pop/docs/Pop.md
  src/components/Pop/docs/Popper.md
  src/components/Pop/docs/Reference.md
  src/components/Pop/index.js
  src/components/Popover/Popover.css.js
  src/components/Popover/Popover.integration.test.js
  src/components/Popover/Popover.jsx
  src/components/Popover/Popover.stories.js
  src/components/Popover/Popover.test.js
  src/components/Popover/README.md
  src/components/Popper/Popper.Manager.jsx
  src/components/Popper/Popper.Reference.jsx
  src/components/Popper/Popper.jsx
  src/components/Popper/Popper.utils.js
  src/components/Popper/README.md
  src/components/Popper/index.js
  src/components/Tooltip/README.md
  src/components/Tooltip/Tooltip.Popper.jsx
  src/components/Tooltip/Tooltip.css.js
  src/components/Tooltip/Tooltip.jsx
  src/components/Tooltip/Tooltip.stories.js
  src/components/Tooltip/Tooltip.test.js
  src/components/Tooltip/__tests__/Tooltip.Pop.test.js
  src/components/Tooltip/__tests__/Tooltip.Popper.test.js
  src/components/Tooltip/__tests__/Tooltip.test.js
  src/components/Tooltip/docs/Popper.md
  src/components/Tooltip/docs/Tooltip.md
  src/components/Tooltip/index.js
  src/components/index.js
  src/utilities/pkg.js
  src/utilities/popper.lib.js
Labels: enhancement ✨, refactor ♻️, v3

#823 PROD-726 Fix Margin Bottom on HSDS Form
  src/components/Form/Form.Actions.css.js
Labels: bug 🐛, patch ☝️

#827 Fix prop-types warnings
  jest.config.js
  package-lock.json
  package.json
  src/components/ArticleCard/ArticleCard.jsx
  src/components/AttachmentList/AttachmentList.jsx
  src/components/Avatar/Avatar.jsx
  src/components/BlankSlate/BlankSlate.jsx
  src/components/BlankSlate/BlankSlate.test.js
  src/components/ChatTranscript/ChatTranscript.Item.jsx
  src/components/Dropdown/Dropdown.jsx
  src/components/EditableField/EditableField.Actions.jsx
  src/components/EditableField/EditableField.Input.jsx
  src/components/EditableField/EditableField.Mask.jsx
  src/components/FilteredList/FilteredList.jsx
  src/components/Illo/Illo.jsx
  src/components/Input/Input.jsx
  src/components/StatusBadge/StatusBadge.jsx
  src/components/Table/Table.Body.jsx
  src/components/Table/Table.Cell.jsx
  src/components/Table/Table.Head.jsx
  src/components/Table/Table.HeaderCell.jsx
  src/components/Table/Table.Row.jsx
  src/components/Table/Table.jsx
  src/components/Table/Table.utils.js
  src/components/Text/Text.jsx
Labels: bug 🐛, enhancement ✨

#828 Hide Storybook Addon Panel by default
  .storybook/manager.js
Labels: tooling :wrench:

#825 PROD-784 Add New copy-small Icon to HSDS (v2)
  src/components/Icon/icons.all.js
  src/icons/copy-small.svg
Labels: enhancement ✨

#824 PROD-726 Fix Margin Bottom on HSDS Form (v2)
  src/components/Form/Actions/Form.Actions.css.js
Labels: bug 🐛, patch ☝️, v2

#829 Fix Dropdown.MenuContainer memory leak
  src/components/Dropdown/Dropdown.MenuContainer.jsx
Labels: bug 🐛

#826 PROD-784 Add New copy-small Icon to HSDS
  src/components/Icon/icons.all.js
  src/icons/copy-small.svg
Labels: enhancement ✨

#830 PROD-816 Update Popover to be able to display on hover
  src/components/Popover/Popover.jsx
  src/components/Popover/Popover.stories.js
Labels: bug 🐛
