Repository helpscout/hsds-react, pull requests merged in 2020-08, with the labels that each got.

#874 CheckMarkCard
  .remake/component/remake-name/remake-name.jsx
  .remake/component/remake-name/remake-name.stories.mdx
  .remake/component/remake-name/remake-name.test.js
  package.json
  src/components/Animate/Animate.stories.mdx
  src/components/AnimateGroup/AnimateGroup.stories.mdx
  src/components/ChatScroller/ChatScroller.stories.mdx
  src/components/CheckMarkCard/CheckMarkCard.css.js
  src/components/CheckMarkCard/CheckMarkCard.jsx
  src/components/CheckMarkCard/CheckMarkCard.stories.mdx
  src/components/CheckMarkCard/CheckMarkCard.test.js
  src/components/CheckMarkCard/index.js
  src/components/Checkbox/Checkbox.jsx
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/ChoiceGroup/ChoiceGroup.jsx
  src/components/ChoiceGroup/ChoiceGroup.test.js
  src/components/Collapsible/Collapsible.stories.mdx
  src/components/ConditionField/ConditionField.stories.mdx
  src/components/ConditionList/ConditionList.stories.mdx
  src/components/Drop/Drop.Positioner.jsx
  src/components/Drop/Drop.jsx
  src/components/Drop/Drop.md
  src/components/EventListener/EventListener.stories.mdx
  src/components/Flexy/Flexy.stories.mdx
  src/components/FormGroup/FormGroup.stories.mdx
  src/components/Frame/Frame.stories.mdx
  src/components/Grid/Grid.stories.mdx
  src/components/HSDS/HSDS.stories.mdx
  src/components/Illo/Illo.stories.mdx
  src/components/Image/Image.stories.mdx
  src/components/InfiniteScroller/InfiniteScroller.stories.mdx
  src/components/Inline/Inline.stories.mdx
  src/components/KeypressListener/KeypressListener.stories.mdx
  src/components/Label/Label.stories.mdx
  src/components/List/List.stories.mdx
  src/components/NotificationStack/NotificationStack.stories.mdx
  src/components/Overflow/Overflow.stories.mdx
  src/components/Overlay/Overlay.stories.mdx
  src/components/Portal/Portal.stories.mdx
  src/components/PortalWrapper/PortalWrapper.stories.mdx
  src/components/RadioCard/RadioCard.css.js
  src/components/RadioCard/RadioCard.jsx
  src/components/RadioCard/RadioCard.stories.mdx
  src/components/RadioCard/RadioCard.test.js
  src/components/ScrollLock/ScrollLock.stories.mdx
  src/components/Scrollable/Scrollable.stories.mdx
  src/components/SleepDetector/SleepDetector.stories.mdx
  src/components/Sortable/Sortable.stories.mdx
  src/components/Truncate/Truncate.stories.mdx
  src/components/VisuallyHidden/VisuallyHidden.stories.mdx
  src/components/index.js
Labels: enhancement ✨, feature 💅

#875 Fixes Popover arrow/tip rendering
  src/components/Popover/Popover.css.js
  src/components/Popover/Popover.jsx
  src/components/Popover/Popover.test.js
  src/components/Tooltip/Tooltip.css.js
  src/components/Tooltip/Tooltip.jsx
Labels: bug 🐛, hot fix 🔥

#877 ChoiceGroup: onChange and onEnter callbacks always receive value wrapped in array but it only should be for multiSelect
  src/components/ChoiceGroup/ChoiceGroup.jsx
  src/components/ChoiceGroup/ChoiceGroup.test.js
Labels: bug 🐛

#878 HSDS-165 Dropdown: update selectedItem propType
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.stories.mdx
Labels: bug 🐛

#879 Fix Checkbox disabled state
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/Choice/Choice.Input.jsx
  src/components/Choice/Choice.css.js
  src/components/ChoiceGroup/ChoiceGroup.jsx
Labels: bug 🐛

#876 Updates for beacon
  src/components/ArticleCard/ArticleCard.css.js
  src/components/Frame/Frame.jsx
  src/components/Icon/icons.embed.js
  src/components/Input/Input.jsx
  src/components/Input/Input.stories.mdx
  src/components/MessageCard/MessageCard.Button.jsx
  src/components/MessageCard/MessageCard.css.js
  src/components/MessageCard/MessageCard.stories.mdx
  src/components/Portal/Portal.jsx
Labels: bug 🐛

#880 Fix Frame performance
  package-lock.json
  package.json
  src/components/Frame/Frame.jsx
  src/components/Frame/Frame.stories.mdx
  src/components/Frame/index.js
  src/utilities/pkg.js
Labels: bug 🐛
