Repository helpscout/hsds-react, pull requests merged in 2021-11, with the labels that each got.

#996 Allow component props to overwrite pagination attributes
  src/components/Pagination/Pagination.jsx
Labels: bug 🐛

#975 New Tag UI
  src/components/ChatList/ChatList.Item.jsx
  src/components/ChatList/ChatList.css.js
  src/components/Tag/Tag.css.js
  src/components/Tag/Tag.jsx
  src/components/Tag/Tag.stories.mdx
  src/components/Tag/Tag.test.js
  src/components/TagList/TagList.css.js
  src/components/TagList/TagList.jsx
  src/components/TagList/TagList.stories.mdx
  src/components/TagList/TagList.storiesHelpers.js
  src/components/TagList/TagList.test.js
  src/utilities/specs/chat.specs.js
  src/utilities/specs/tags.specs.js
Labels: enhancement ✨, a11y

#997 Fix tag remove icon border-radius
  src/components/Tag/Tag.css.js
Labels: bug 🐛

#1000 Improve accessibility for Condition Select element
  src/components/Condition/Condition.jsx
  src/components/Condition/Condition.test.js
Labels: enhancement ✨, a11y

#998 HSAPPUI-310: Add onInputChange callback to DropList
  src/components/DropList/DropList.Combobox.jsx
  src/components/DropList/DropList.jsx
  src/components/DropList/DropList.test.js
Labels: feature 💅
