Repository helpscout/hsds-react, pull requests merged in 2021-12, with the labels that each got.

#1006 trapped focus and ChoiceGroup fixes
  package-lock.json
  package.json
  src/components/CheckMarkCard/CheckMarkCard.jsx
  src/components/CheckMarkCard/CheckMarkCard.stories.mdx
  src/components/CheckMarkCard/CheckMarkCard.test.js
  src/components/ChoiceGroup/ChoiceGroup.jsx
  src/components/ChoiceGroup/ChoiceGroup.test.js
  src/components/SimpleModal/SimpleModal.stories.mdx
  src/components/SimpleModal/SimpleModal.storiesHelpers.js
  src/utilities/focus.js
Labels: bug 🐛

#1008 Call onLoad for Avatar in constructor, when image already in cache
  src/components/Avatar/Avatar.Image.jsx
  src/components/Avatar/Avatar.test.js
Labels: enhancement ✨

#1009 Fix enter/space keypress for Radio input
  src/components/Choice/Choice.Input.jsx
  src/components/Choice/ChoiceInput.test.js
Labels: bug 🐛

#1010 New CopyValue Component
  src/components/CopyButton/CopyButton.jsx
  src/components/CopyButton/CopyButton.utils.js
  src/components/CopyValue/CopyValue.css.js
  src/components/CopyValue/CopyValue.js
  src/components/CopyValue/CopyValue.stories.mdx
  src/components/CopyValue/CopyValue.test.js
  src/components/CopyValue/index.js
  src/components/HSDS/GlobalStyle.js
  src/components/Tag/Tag.css.js
  src/components/TagList/TagList.css.js
  src/components/VerificationCode/VerificationCode.css.js
Labels: feature 💅
