Repository helpscout/hsds-react, pull requests merged in 2021-05, with the labels that each got.

#927 HSDS-187 Update emoticon face to increase contrast
  src/components/Emoticon/Emoticon.css.js
Labels: a11y

#925 Update state-based input focus styling
  src/components/Input/Input.BackdropV2.css.js
  src/components/Input/Input.stories.mdx
Labels: enhancement ✨

#928 HSDS-188 Rename the `title` prop to `initials` in AvatarImage component
  src/components/Avatar/Avatar.Image.jsx
  src/components/Avatar/Avatar.css.js
  src/components/Avatar/Avatar.jsx
  src/components/Avatar/Avatar.test.js
Labels: bug 🐛

#930 BEMBED-275: Helpscout chat modal color contrast
  package-lock.json
  package.json
  src/styles/utilities/color.js
  src/utilities/__tests__/color/contrast.test.js
  src/utilities/__tests__/color/getColorShade.test.js
  src/utilities/__tests__/color/luminance.test.js
  src/utilities/__tests__/color/optimalTextColor.test.js
  src/utilities/color.js
Labels: a11y

#932 HSDS-186 new CheckmarkCard UI
  package-lock.json
  src/components/CheckMarkCard/CheckMarkCard.css.js
  src/components/CheckMarkCard/CheckMarkCard.jsx
  src/components/CheckMarkCard/CheckMarkCard.stories.mdx
  src/components/CheckMarkCard/CheckMarkCard.test.js
Labels: enhancement ✨

#929 HSDS-189 Update helix to 0.2.0
  package-lock.json
  package.json
Labels: enhancement ✨

#931 Fixed prop types on MessageCard image width and height to avoid console error
  src/components/MessageCard/MessageCard.jsx
Labels: bug 🐛
