Repository helpscout/hsds-react, pull requests merged in 2021-07, with the labels that each got.

#950 Update react-router to newest version and change not compatible components
  package-lock.json
  package.json
  src/components/Button/Button.stories.mdx
  src/components/Button/Button.test.js
  src/components/Drop/Drop.test.js
  src/components/Link/Link.stories.mdx
  src/components/Link/Link.test.js
  src/components/Modal/__tests__/Modal.integration.test.js
  src/components/NavLink/NavLink.jsx
  src/components/PortalWrapper/PortalWrapper.jsx
  src/components/PortalWrapper/PortalWrapper.test.js
  src/components/Route/Route.jsx
  src/components/Route/index.js
  src/components/RouteWrapper/RouteWrapper.integration.test.js
  src/components/RouteWrapper/RouteWrapper.jsx
  src/components/RouteWrapper/RouteWrapper.test.js
  src/components/Table/Table.testUtils.js
  src/components/WithRouterCheck/WithRouterCheck.js
  src/components/WithRouterCheck/index.js
  src/components/index.js
  src/tests/libraries/helix/createSpec.test.js
  src/tests/libraries/helix/faker.test.js
  src/utilities/pkg.js
  src/utilities/specs/chat.specs.js
Labels: enhancement ✨

#951 [DropList] Fix crash when a divider item type is present and you type a character
  src/components/DropList/DropList.utils.js
Labels: bug 🐛

#953 Allow ActionSelect component to be disabled and to provide ID
  src/components/ActionSelect/ActionSelect.jsx
  src/components/ActionSelect/ActionSelect.test.js
Labels: a11y, enhancement ✨

#955 Replace Select component with DropList in Condition
  src/components/Condition/Condition.css.js
  src/components/Condition/Condition.jsx
  src/components/Condition/Condition.storiesHelpers.js
  src/components/Condition/Condition.test.js
  src/components/ConditionField/ConditionField.jsx
Labels: enhancement ✨

#957 Fixes Droplist scrolling the document
  src/components/DropList/DropList.jsx
Labels: bug 🐛
