Repository helpscout/hsds-react, pull requests merged in 2022-01, with the labels that each got.

#1013 HSDS-229: MessageCard body variable transformer
  src/components/MessageCard/MessageCard.css.js
  src/components/MessageCard/MessageCard.jsx
  src/components/MessageCard/MessageCard.stories.mdx
  src/components/MessageCard/MessageCard.test.js
  src/components/MessageCard/components/MessageCard.Body.jsx
  src/components/MessageCard/utils/MessageCard.utils.js
  src/components/MessageCard/utils/MessageCard.utils.test.js
Labels: feature 💅

#1014 Allow Collabsible/Accordion.Body content to be pre-rendered
  src/components/Accordion/Accordion.Body.jsx
  src/components/Accordion/__tests__/Accordion.Body.test.js
  src/components/Collapsible/Collapsible.jsx
  src/components/Collapsible/Collapsible.test.js
  src/components/SidePanel/SidePanel.layouts.jsx
Labels: enhancement ✨

#1015 Fix Message Card variable regex so that it's possible to include % sign in fallback
  src/components/MessageCard/utils/MessageCard.utils.js
  src/components/MessageCard/utils/MessageCard.utils.test.js
Labels: bug 🐛

#1018 Fix aria-describedby attribute on Choice component to use id, not raw text
  src/components/Choice/Choice.Input.jsx
  src/components/Choice/Choice.jsx
  src/components/Choice/Choice.test.js
Labels: bug 🐛, a11y

#1019 Do not set aria-describedby on Choice input when no helpText
  src/components/Choice/Choice.jsx
  src/components/Choice/Choice.test.js
Labels: a11y

#1020 Add ordered-list and handwave to icon set
  src/components/Icon/icons.all.js
  src/icons/handwave.svg
  src/icons/list.svg
  src/icons/ordered-list.svg
Labels: enhancement ✨
