Repository helpscout/hsds-react, pull requests merged in 2022-05, with the labels that each got.

#1056 Rewrite Icons CSS & New Docs Icons
  package-lock.json
  package.json
  src/components/Icon/Icon.css.js
  src/components/Icon/Icon.storiesHelpers.js
  src/components/Icon/icons.all.js
  src/icons/blockquote.svg
  src/icons/callout.svg
  src/icons/circle-arrow.svg
  src/icons/code.svg
  src/icons/dl.svg
  src/icons/drag-handle.svg
  src/icons/h1.svg
  src/icons/table-left.svg
  src/icons/table-top.svg
Labels: bug 🐛, enhancement ✨

#1058 HSDS-250 HSDS-254 HSDS-264: Faces Survey Component + Updated Thumbs Survey
  src/components/Emoticon/Emoticon.css.js
  src/components/Emoticon/Emoticon.icons.js
  src/components/Emoticon/Emoticon.jsx
  src/components/MessageCard/MessageCard.Survey.context.js
  src/components/MessageCard/MessageCard.Survey.variants.js
  src/components/MessageCard/MessageCard.css.js
  src/components/MessageCard/MessageCard.stories.mdx
  src/components/MessageCard/components/MessageCard.Survey.Faces.jsx
  src/components/MessageCard/components/MessageCard.Survey.Faces.test.js
  src/components/MessageCard/components/MessageCard.Survey.Thumbs.jsx
  src/components/MessageCard/components/MessageCard.Survey.css.js
  src/components/MessageCard/components/MessageCard.Survey.jsx
  src/components/MessageCard/utils/MessageCard.hooks.js
  src/components/RateAction/RateAction.css.js
  src/components/RateAction/RateAction.jsx
  src/components/RateAction/RateAction.stories.mdx
  src/components/Tooltip/Tooltip.jsx
Labels: enhancement ✨, feature 💅

#1060 HSDS-262 New Filtered badge UI
  src/components/Badge/Badge.jsx
  src/components/FilteredList/FilteredList.css.js
  src/components/FilteredList/FilteredList.jsx
  src/components/FilteredList/FilteredList.test.js
Labels: enhancement ✨

#1061 HSD- 261 Update CheckmarkCard disabled UI
  src/components/CheckMarkCard/CheckMarkCard.css.js
  src/components/CheckMarkCard/CheckMarkCard.jsx
  src/components/CheckMarkCard/CheckMarkCard.stories.mdx
  src/components/CheckMarkCard/CheckMarkCard.test.js
Labels: enhancement ✨

#1064 HSDS-256: Microsurveys: MultipleChoiceSurvey Component
  .storybook/storybook.css
  src/components/Emoticon/Emoticon.css.js
  src/components/Emoticon/Emoticon.jsx
  src/components/MessageCard/MessageCard.Survey.variants.js
  src/components/MessageCard/MessageCard.jsx
  src/components/MessageCard/MessageCard.stories.mdx
  src/components/MessageCard/MessageCard.storiesHelper.js
  src/components/MessageCard/components/survey/MessageCard.Survey.Faces.jsx
  src/components/MessageCard/components/survey/MessageCard.Survey.Faces.test.js
  src/components/MessageCard/components/survey/MessageCard.Survey.MultipleChoice.jsx
  src/components/MessageCard/components/survey/MessageCard.Survey.MultipleChoice.test.js
  src/components/MessageCard/components/survey/MessageCard.Survey.Thumbs.jsx
  src/components/MessageCard/components/survey/MessageCard.Survey.css.js
  src/components/MessageCard/components/survey/MessageCard.Survey.jsx
  src/components/MessageCard/utils/MessageCard.Survey.context.js
  src/components/RateAction/RateAction.jsx
Labels: feature 💅

#1066 Fix survey issues
  package-lock.json
  package.json
  src/components/MessageCard/MessageCard.stories.mdx
  src/components/MessageCard/MessageCard.test.js
  src/components/MessageCard/components/survey/MessageCard.Survey.MultipleChoice.jsx
  src/components/MessageCard/components/survey/MessageCard.Survey.css.js
  src/components/MessageCard/components/survey/MessageCard.Survey.jsx
  src/utilities/pkg.js
Labels: bug 🐛

#1067 Improve focus states for Messages survey components
  src/components/MessageCard/MessageCard.css.js
  src/components/MessageCard/components/survey/MessageCard.Survey.css.js
Labels: enhancement ✨, a11y

#1069 SimpleModal (confirmation layout): Swap which buttons handlers are applied to
  src/components/SimpleModal/SimpleModal.layouts.jsx
Labels: feature 💅, hot fix 🔥
